### ISSUE TITLE
Hanging builds on windows-latest, jdk 8, adopt-openj9

### ISSUE THREAD

**Issue by kriegaex** [actions/setup-java#211] opened 2021-08-24 15:20 UTC
**Description:**
After upgrading from 2.2.0 to 2.3.0, this combination reproducible hangs and builds time out, if I do not interrupt them manually.

**Task version:**
2.3.0
**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
See
  * https://github.com/dev-aspectj/aspectj-maven-plugin/actions/runs/1159187731
  * https://github.com/dev-aspectj/aspectj-maven-plugin/actions/runs/1162919257
  * https://github.com/dev-aspectj/aspectj-maven-plugin/actions/runs/1162997322
  * https://github.com/dev-aspectj/aspectj-maven-plugin/actions/runs/1163075387

In all of the above cases, this specific combination of OS, Java version and JVM type hangs. All the other matrix combinations run as expected.

**Comment by kriegaex** [comment] 2021-08-24 15:41
Hm, I reverted, but again the build hangs for windows-latest, jdk 8, adopt-openj only:

https://github.com/dev-aspectj/aspectj-maven-plugin/runs/3412728723?check_suite_focus=true

Maybe the problem is not caused by this action, but I have no idea how to start debugging it. Please help. I am sure, as maintainer of this action you know better what the root cause might be.

**Comment by kriegaex** [comment] 2021-08-24 15:47
I found [this log](https://pipelines.actions.githubusercontent.com/brtuznieUMMPhs3p8BhXpzYNB3rlE2319R83TmlAkfCoFxwfBm/_apis/pipelines/1/runs/81/signedlogcontent/18?urlExpires=2021-08-24T15%3A42%3A51.8844201Z&urlSigningMethod=HMACV1&urlSignature=8qTvOK76x4ZNpBQNrm42jPv5M6Pw7scgmMK%2FT0OWmZ8%3D):

```text
2021-08-24T15:23:02.7536798Z Found online and idle hosted runner in the current repository's organization account that matches the required labels: 'windows-latest'
2021-08-24T15:23:02.8081614Z Waiting for a Hosted runner in the 'organization' to pick this job...
2021-08-24T15:24:03.4898762Z Job was not picked up by the preferred runner, try request addition runners to run this job
2021-08-24T15:24:03.8445436Z Waiting for a self-hosted runner to pickup this job...
2021-08-24T15:26:02.7706208Z Job is waiting for a hosted runner to come online.
2021-08-24T15:26:06.4324593Z Job is about to start running on the hosted runner: GitHub Actions 14 (hosted)
```

Do you know what it means and if there is any way for me to reset or restart that runner?

Please also note that my own repository is not the only one affected by this, see also the upstream project:

https://github.com/mojohaus/aspectj-maven-plugin/runs/3406772496?check_suite_focus=true

There, we can see a bit more in the log (in my logs there is nothing):

```text
Run mvn -N "io.takari:maven:0.7.7:wrapper" "-Dmaven=3.3.9"
  mvn -N "io.takari:maven:0.7.7:wrapper" "-Dmaven=3.3.9"
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
  env:
    JAVA_HOME: C:\hostedtoolcache\windows\Java_Adopt-OpenJ9_jdk\8.0.302-8\x64
Unhandled exception
Type=Segmentation error vmState=0x00000000
Windows_ExceptionCode=c0000139 J9Generic_Signal=00000004 ExceptionAddress=00007FFE3CC9EE08 ContextFlags=0010000f
Handler1=00007FFE0D4FCBE0 Handler2=00007FFE0DE493A0
RDI=00000185B200FE58 RSI=00007FFE3CD187B0 RAX=00007FFE0000006C RBX=00000000C0000139
RCX=0000000000000048 RDX=00007FFE00000001 R8=00007FFE3CC23A03 R9=00007FFE3CC25886
R10=0000007E0DDFC300 R11=0000000000000000 R12=0000000000000003 R13=0000000000000003
R14=0000000000000001 R15=0000000000000003
RIP=00007FFE3CC9EE08 RSP=0000007E0DDFC140 RBP=0000007E0DDFC7E0 EFLAGS=0DDFC40000000202
FS=0053 ES=002B DS=002B
XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM1 0000000001000040 (f: 16777280.000000, d: 8.289078e-317)
XMM2 0057005c003a0043 (f: 3801155.000000, d: 5.117982e-307)
XMM3 0053005c00730077 (f: 7536759.000000, d: 4.227953e-307)
XMM4 005c00320033004d (f: 3342413.000000, d: 6.230377e-307)
XMM5 0065007300610062 (f: 6357090.000000, d: 9.346091e-307)
XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
Module=C:\Windows\SYSTEM32\ntdll.dll
Module_base_address=00007FFE3CC00000 Offset_in_DLL=000000000009ee08
Target=2_90_20210730_192 (Windows Server 2019 10.0 build 17763)
CPU=amd64 (2 logical CPUs) (0x1bff8d000 RAM)
----------- Stack Backtrace -----------
Error: The operation was canceled.
```

**Comment by maxim-lobanov** [comment] 2021-08-24 16:03
Hello @kriegaex, 
Could you please check logs of setup-java step in failed and successful build?
Logs should contain the exact version that is downloaded.

I suspect that new version of Adopt OpenJ9 could be released and cause it.

**Comment by kriegaex** [comment] 2021-08-24 16:30
@maxim-lobanov, why don't you check the logs? You are much more experienced with this action than I am. You can easily navigate from the logs I linked to to the list of workflow runs and inspect each and every detail in my public logs.

But actually, I just had the same idea as you before, comparing the setup logs from the [last green build](https://github.com/dev-aspectj/aspectj-maven-plugin/runs/3288478982?check_suite_focus=true)
```text
Run actions/setup-java@v2.2.0
Resolved Java 8.0.292+10 from tool-cache
Setting Java 8.0.292+10 as the default

Java configuration:
  Distribution: adopt-hotspot
  Version: 8.0.292+10
  Path: C:\hostedtoolcache\windows\Java_Adopt_jdk\8.0.292-10\x64

Creating settings.xml with server-id: github
Writing to C:\Users\runneradmin\.m2\settings.xml
```

to [one of the hanging ones](https://github.com/dev-aspectj/aspectj-maven-plugin/runs/3401830497?check_suite_focus=true):
```text
Run actions/setup-java@v2.3.0
Trying to resolve the latest version from remote
Resolved latest version as 8.0.302+8
Trying to download...
Downloading Java 8.0.302+8 (Adopt-OpenJ9) from https://github.com/AdoptOpenJDK/semeru8-binaries/releases/download/jdk8u302-b08_openj9-0.27.0/ibm-semeru-open-jdk_x64_windows_8u302b08_openj9-0.27.0.zip ...
Extracting Java archive...
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\4471ec7e-3c21-41b3-baf3-51d886e1067c', 'D:\a\_temp\6ca77cc1-069c-4f90-bb93-14a03b10a620')"
Java 8.0.302+8 was downloaded
Setting Java 8.0.302+8 as the default

Java configuration:
  Distribution: adopt-openj9
  Version: 8.0.302+8
  Path: C:\hostedtoolcache\windows\Java_Adopt-OpenJ9_jdk\8.0.302-8\x64

Creating settings.xml with server-id: github
Writing to C:\Users\runneradmin\.m2\settings.xml
```

It looks as if your educated guess was right, the problem might be related to the adopt-hotspot version upgrade from 8.0.292+10 to 8.0.302+8, specifically on Windows. Is this something that can be fixed in this action, or is the archive broken? What are you recommending me to do? Use a fixed version instead of latest? That would not be nice, albeit a temporary workaround.

**Comment by maxim-lobanov** [comment] 2021-08-24 17:02
@kriegaex, first of all, please try to specify the previous version explicitly to see if it fixes your build or not. Version input of action supports format `8.0.292+10`.
If it fixes your build, it means that issue is related to new version package provided by Adopt. In this case, I suggest reporting this issue to Adopt OpenJDK team and wait for the fix from their side. During that, it is better to have hardcoded version to make sure that you are not blocked by that.

**Comment by kriegaex** [comment] 2021-08-25 09:38
Downgrading to the version which used to work before, also does not work, I have no idea why:
https://github.com/dev-aspectj/aspectj-maven-plugin/runs/3420238819?check_suite_focus=true

Something with Adopt Open9 JDK 8 on Windows seems to be fundamentally broken.

**Comment by dmitry-shibanov** [comment] 2021-08-30 14:28
Hello @kriegaex. Sorry for the late reply. We investigated the issue from our side, but for now we have no idea what is the root cause of the issue. We'll let you know if we find something

**Comment by kriegaex** [comment] 2021-08-30 15:43
FYI, I created https://support.github.com/ticket/personal/0/1290814, which probably you cannot access. Let's see what GH support says. If I have any new insights, I am also going to keep you posted here.

**Comment by maxim-lobanov** [comment] 2021-08-30 16:15
A few thoughts from our side:
- Nothing was changed from Adopt OpenJDK binaries side
- Nothing was changed from actions/setup-java side
- No related changes are done on VMs side

Also our suspicious was any project dependencies but we didn't find anything related.
The most interesting thing is that only OpenJ9 for Java 8 is affected and we can't imagine what could be the root cause of it.
Any changes on VM side or setup-java would affect all versions of Java.

**Comment by dmitry-shibanov** [comment] 2021-09-16 12:15
Hello @kriegaex. Could you please try to use this snippet:
```
      - name: Build with Maven
        shell: pwsh
        run: |
          if($IsWindows) {
            $JAVA_BIN_PATH = Join-Path $env:JAVA_HOME bin
            $env:PATH = "C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.2\bin;$JAVA_BIN_PATH"
          }
          mvn --show-version --errors --batch-mode "-Dinvoker.streamLogsOnFailures=true" clean verify site

```

**Comment by kriegaex** [comment] 2021-09-16 15:36
The [build passed](https://github.com/dev-aspectj/aspectj-maven-plugin/runs/3622122606?check_suite_focus=true) - intriguing! This has been the first build in weeks which was successful.

Would you please explain the rationale behind your suggestion? And what conslusions can you draw from it? Is this somehow related to what I can reproduce locally, as explained in https://github.com/adoptium/adoptium-support/issues/350#issuecomment-916665876 and subsequent comments?

**Comment by dmitry-shibanov** [comment] 2021-09-20 09:22
Hello @kriegaex. Thank you for your response. The root cause of the issue comes from `choco kotlin` installation. It modified path variable and added its own jdk. I think `adopt-openj9` had conflicts . The installation of kotlin was reworked. I think your builds should start to pass after the  next images rollout. 
I'll keep the issue open, until the [issue](https://github.com/actions/virtual-environments/issues/4089) from virtual environments is closed.

**Comment by dmitry-shibanov** [comment] 2021-09-24 10:06
Hello @kriegaex. The images is updated and your build should start to pass with the latest `openj9`.
For now I'm closing the issue. If you have any concerns feel free to ping us.

**Closed by dmitry-shibanov** 2021-09-24 10:06 UTC
Labels: bug

**Comment by kriegaex** [comment] 2021-09-26 11:43
I am confirming that it works again now, see https://github.com/dev-aspectj/aspectj-maven-plugin/actions/runs/1275057263.
