### ISSUE TITLE
action sometimes throws "Could not load manifest for Microsoft Build of OpenJDK"

### ISSUE THREAD

**Issue by Bestyan** [actions/setup-java#645] opened 2024-07-09 12:58 UTC
**Description:**
Sometimes the action fails with an error message like this (output from the github workflow):
```
Run actions/setup-java@v4
  with:
    java-version: 21.0.1
    distribution: microsoft
    java-package: jdk
    check-latest: false
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true
    job-status: success
  env:
    GH_TOKEN: ***
Installed distributions
  Trying to resolve the latest version from remote
  Error: Could not load manifest for Microsoft Build of OpenJDK
```
It is only sometimes though, if I wait an hour and try it again, chances are, it's working again.
When I try to download the `.tar.gz` archive manually during a period where the action is not working, the download link is working fine.

**Task version:**
`v4`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Repro steps:**  
I am unable to consistently reproduce this behaviour as it only happens sometimes and I don't know why.
I haven't encountered any problems so far if I manually download the `.tar.gz` archive and feed that into the `setup-java` action.

**Expected behavior:**
Work consistently.

**Actual behavior:**
Works sometimes, sometimes not for unknown reasons.

**Comment by priyagupta108** [comment] 2024-07-10 05:10
Hello @Bestyan,
Thank you for reporting this. We will investigate the issue and get back to you as soon as we have updates.

**Comment by aparnajyothi-y** [comment] 2024-07-29 12:28
Hello @Bestyan, Thank once again for creating this issue and we tried reproducing this issue but we are not able to. Please find the screenshots for reference.
It would be very helpful if we could obtain the detailed logs of the failed run or a repro link to a public repository that reproduces the problem . As we understand from your description, the issue is not consistent, and these logs would aid us in identifying the root cause more effectively.

![Image](https://github.com/user-attachments/assets/e2b280f3-29f3-4a1f-ac3b-fb18a5133965)

**Comment by Bestyan** [comment] 2024-08-06 15:07
Hi @aparnajyothi-y,
it hasn't happened in a while now. However, I dug up a run that had debug logs enabled. Unfortunately there isn't much to go on:

```
Run actions/setup-java@v4
  with:
    java-version: 21.0.1
    distribution: microsoft
    java-package: jdk
    check-latest: false
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true
    job-status: success
::group::Installed distributions
Installed distributions
  Trying to resolve the latest version from remote
  ##[debug]Http request for microsoft-openjdk-versions.json failed with status code: undefined
  Error: Could not load manifest for Microsoft Build of OpenJDK
  ##[debug]Node Action run completed with exit code 1
  ##[debug]Finishing: Setup MS JDK 21.0.1
```

**Comment by aparnajyothi-y** [comment] 2024-08-08 06:30
Hello @Bestyan, Thank you for your response. We understand that the issue is not currently happening and we have also been unable to reproduce it. We suspect the error could be due to one of the following scenarios:

- Network Issues: There might be network connectivity issues preventing the HTTP request from reaching the server.
- Server Downtime: The server hosting microsoft-openjdk-versions.json might be down or experiencing issues.
- Firewall or Proxy: A firewall or proxy might be blocking the request.

To confirm the root cause, could you please provide the self-hosted runner logs by following these steps:

- Navigate to the Runner Directory: Go to the directory where the self-hosted runner is installed.
- Check the _diag Directory: Within the runner installation directory, find the _diag directory. It contains diagnostic logs.

Please feel free to reach out to us if you have any further concerns or need additional clarification.

**Comment by Bestyan** [comment] 2024-08-14 21:30
Hi, thanks for the suggestions. I can safely exclude 2 of them:

> Server Downtime: The server hosting microsoft-openjdk-versions.json might be down or experiencing issues.

while this was happening, I was able to manually download the jdk from the source, using the same link the action uses

> Firewall or Proxy: A firewall or proxy might be blocking the request.

unlikely, as this is/was a temporary issue that went away after a while. It wasn't happening in our china environment either.

> Network Issues: There might be network connectivity issues preventing the HTTP request from reaching the server.

Maybe this is it.

I'll try to get access to the logs if it happens again.
Thank you for your efforts <3

**Comment by aparnajyothi-y** [comment] 2024-08-22 04:04
Hello @Bestyan, Thank you for the confirmation that the issue resolved hence closing this issue. Please feel free to reach us in case of any further issues/concerns to reopen this issue.

**Closed by aparnajyothi-y** 2024-08-22 04:04 UTC
Labels: bug
