### ISSUE TITLE
Release 3.7.0 was deleted

### ISSUE THREAD

**Issue by fgarsombke** [actions/setup-java#422] opened 2022-12-05 16:57 UTC
We have just moved all of our builds to `actions/setup-java@v3.7.0` and it just disappeared so they are all failing.

Do we need to revert everything back to `actions/setup-java@v3.6.0` or is this going to be replaced?

Thanks.

**Comment by ArloL** [comment] 2022-12-05 17:57
Looks like the intention was to remove the oracle jdk feature by rolling back 3.7.0. Would have been great to roll forward to 4.0.0 instead since the removal is a breaking change.

**Comment by JakeWharton** [comment] 2022-12-05 18:17
With the presence of tools like Dependabot and Renovate hundreds of repositories migrated and are now broken: https://github.com/search?q=%22actions%2Fsetup-java%40v3.7.0%22&type=code

**Comment by PatrickGotthard** [comment] 2022-12-06 07:53
Please just tag 3.6.0 also as 3.7.0 to fix the majority of problems. All our actions were updated automatically and it would cost much time to downgrade them manually 🫤

**Comment by DanySK** [comment] 2022-12-06 08:06
Wow, this destroyed dozens of my pipelines. Please, please, never delete releases anymore :pray:

**Comment by jdrphillips** [comment] 2022-12-06 08:08
It's worrying that this is possible. 3.7.0 could be re-released with any code at all - if they had been malicious this could have happened quickly after most of us had auto-upgraded and it would have slipped through without anyone noticing

**Comment by ArloL** [comment] 2022-12-06 08:29
> It's worrying that this is possible.

Just to be certain: That is a GitHub Actions design decision and not an issue of the setup-java maintainers. This can happen with any action you use. If that is of concern you should switch to using the commit id of the action.

**Comment by Gakk** [comment] 2022-12-06 14:44
Approx. 15 minutes ago a new [version 3.8.0 was released](https://github.com/actions/setup-java/pull/421#issuecomment-1339464740) 😃

**Comment by fgarsombke** [comment] 2022-12-06 14:52
I guess we are updating a few dozen repositories this morning :smiling_face_with_tear: ...

**Comment by garydgregory** [comment] 2022-12-08 21:33
It happened to all of the Apache Commons repositories, not fun.

**Comment by panticmilos** [comment] 2023-01-09 11:22
Hello everyone. As you all are probably aware, the legal points of OracleJdk still need to be tackled and we had to delete this release of the new distribution. I would like to apologize for the inconvenience it has introduced to many of our customers, and we will do our best to prevent similar incidents from happening in the future.

Thank you for understanding the situation, I will close this issue for now.

**Closed by panticmilos** 2023-01-09 11:22 UTC
Labels: bug

**Comment by dmitry-shibanov** [comment] 2023-02-07 17:29
Hello everyone. We had discussions with Oracle teams and confirmed that we can add support for Oracle OpenJDK. We've released a new [version](https://github.com/actions/setup-java/releases/tag/v3.10.0) of the action with support of Oracle OpenJDK. We are sorry for the confusion.
