### ISSUE TITLE
Setting up Java 11 returns Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by sanju349** [actions/setup-java#473] opened 2023-03-26 06:08 UTC
Hello Team,

I am setting up Java 11 on my Windows GitHub Actions runner, but getting Error: self signed certificate in certificate chain. 
Kindly assist you on it. 

Sample workflow:
- name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt-hotspot'
          java-version: '11'

Thanks in advance.
![image](https://user-images.githubusercontent.com/44389483/227758384-fb262a8b-547f-4137-a358-318c4d693c3b.png)

**Comment by IvanZosimov** [comment] 2023-03-27 12:53
Hi, @sanju349  👋 ! Thanks for the issue, we will investigate it and get back to you with updates!

**Comment by IvanZosimov** [comment] 2023-03-28 10:50
Hi, @sanju349  👋 As the problem is resolved now, I'm going to close this issue. Thanks for the fast reaction! ❤️

**Closed by IvanZosimov** 2023-03-28 10:50 UTC
Labels: bug

**Comment by buehlerjochen** [comment] 2024-01-18 06:55
@sanju349 @IvanZosimov How has the problem been resolved?
We are facing the same problem on a Linux GH Actions runner behind company proxy and would really be interested in the solution.

**Comment by jihuncha** [comment] 2024-03-12 11:57
same issue occur to me. any update??

**Comment by buehlerjochen** [comment] 2024-03-13 08:24
In our setup behind company proxy the issue was caused by a missing whitelisting of the Azul D/L URLs. After we added that to the proxy/firewall it worked fine.
However, the error message is not very helpful and I never could figure out if the proxy messed with the Azul certificate or if this is just a misleading error message when the action could not get any traffic from the website.
