### ISSUE TITLE
The supplied javaHome seems to be invalid

### ISSUE THREAD

**Issue by ScottPierce** [actions/setup-java#440] opened 2023-01-07 23:17 UTC
**Description:**
We've been using the setup java task fine for months. An issue has started recently though, and the exact cause isn't clear.

**Task version:**
```
    steps:
      - name: Setup JVM
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
```

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Repro steps:**  
I have a simple example:
```yaml
jobs:
  build-internal-msi:
    name: Build Internal MSI
    runs-on: [ self-hosted, Windows ]

    steps:
      - name: Setup JVM
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download WixTools
        run: ./gradlew unzipWixPatch --stacktrace
```

The Setup JVM step succeeds:
```
Run actions/setup-java@v3
Installed distributions
Creating settings.xml with server-id: github
Overwriting existing file C:\Windows\system32\config\systemprofile\.m2\settings.xml
```

The Download WixTools Fails horribly:
```
Run ./gradlew unzipWixPatch --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
The supplied javaHome seems to be invalid. I cannot find the java executable. Tried location: C:\github-actions\runner2\_work\_tool\Java_Corretto_jdk\[1](https://github.com/company/project/actions/runs/3863848146/jobs/6587016979#step:4:1)7.0.5.8.1\x64\bin\java.exe

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.internal.jvm.JavaHomeException: The supplied javaHome seems to be invalid. I cannot find the java executable. Tried location: C:\github-actions\runner2\_work\_tool\Java_Corretto_jdk\[17](https://github.com/company/project/actions/runs/3863848146/jobs/6587016979#step:4:18).0.5.8.1\x64\bin\java.exe
	at org.gradle.internal.jvm.Jvm.findExecutable(Jvm.java:[18](https://github.com/company/project/actions/runs/3863848146/jobs/6587016979#step:4:19)3)
	at org.gradle.internal.jvm.Jvm.getJavaExecutable(Jvm.java:208)
	at org.gradle.internal.jvm.Jvm.forHome(Jvm.java:1[19](https://github.com/company/project/actions/runs/3863848146/jobs/6587016979#step:4:20))
	at org.gradle.launcher.daemon.context.DaemonCompatibilitySpec.javaHomeMatches(DaemonCompatibilitySpec.java:64)
	at org.gradle.launcher.daemon.context.DaemonCompatibilitySpec.whyUnsatisfied(DaemonCompatibilitySpec.java:40)
	at org.gradle.launcher.daemon.context.DaemonCompatibilitySpec.isSatisfiedBy(DaemonCompatibilitySpec.java:35)
	at org.gradle.launcher.daemon.context.DaemonCompatibilitySpec.isSatisfiedBy(DaemonCompatibilitySpec.java:25)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.getCompatibleDaemons(DefaultDaemonConnector.java:192)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connectToIdleDaemon(DefaultDaemonConnector.java:157)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connectToCanceledDaemon(DefaultDaemonConnector.java:171)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.connect(DefaultDaemonConnector.java:131)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:145)
	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:99)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:57)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:[21](https://github.com/company/project/actions/runs/3863848146/jobs/6587016979#step:4:22)0)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:259)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:[23](https://github.com/company/project/actions/runs/3863848146/jobs/6587016979#step:4:24)0)
	at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:82)
	at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:30)
	at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:96)
	at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:40)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:44)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:[26](https://github.com/company/project/actions/runs/3863848146/jobs/6587016979#step:4:27))
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:361)
	at org.gradle.launcher.Main.doAction(Main.java:35)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:[34](https://github.com/company/project/actions/runs/3863848146/jobs/6587016979#step:4:35))
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:[35](https://github.com/company/project/actions/runs/3863848146/jobs/6587016979#step:4:36))
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:[63](https://github.com/company/project/actions/runs/3863848146/jobs/6587016979#step:4:64))


* Get more help at https://help.gradle.org/
Error: Process completed with exit code 1.
```

**Expected behavior:**
Java 17 is installed and runs correctly

**Actual behavior:**
There is an issue of some sort.

I wonder if there is a race condition of some sort happening. We have 2 Self-hosted github runners running directly on this machine. It hasn't produced an issue until recently, but maybe that's what's causing this?

I noticed this message in the logs:
```
Overwriting existing file C:\Windows\system32\config\systemprofile\.m2\settings.xml
```

Both windows runners (which are running at the same time) would be writing to this file around the same time.

**Comment by panticmilos** [comment] 2023-01-09 09:07
hi @ScottPierce, thank you for the report. We will take a look at it :)

**Comment by panticmilos** [comment] 2023-01-12 14:37
Hi @ScottPierce, I had issues reproducing this behavior. But given the message from the logs that you left, I would agree there is the possibility of race conditions happening. I am wondering if we would add some delay between the jobs these runners are doing, could we trigger the same error?

**Comment by ScottPierce** [comment] 2023-01-14 21:50
In order to work around this, I've moved to a different approach from installing the JVM locally.

**Comment by panticmilos** [comment] 2023-01-18 15:12
hi @ScottPierce, since we are not able to reproduce this issue, and you found the workaround I will close it for now. 

But feel free to reopen it and continue the conversation if you get some new findings about this.

**Closed by panticmilos** 2023-01-18 15:12 UTC
Labels: bug
