### ISSUE TITLE
Maven cache not working

### ISSUE THREAD

**Issue by gdrouet** [actions/setup-java#217] opened 2021-09-03 08:45 UTC
**Description:**
Maven always download the dependencies even if the cache is created

**Task version:**
v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

```
      - name: Setup java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          check-latest: true
          cache: 'maven'
      - run: mvn jacoco:report clean package
```

**Expected behavior:**
After a first execution, the cache should contain all my dependencies and be already on the disk for the next execution of mvn command.

**Actual behavior:**
Dependencies are still downloaded.

```
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/cba13e92-7e18-4a5b-831a-2516c488fb74/cache.tzst -P -C /home/runner/work/dst--backoffice-consumer/dst--backoffice-consumer
Cache restored successfully
Cache restored from key: setup-java-Linux-maven-5f5e8c790dbd1362edf8553421a3c7c1d75d42ca90ded98d3f4e4cd4450a9dea
```

I modified my `pom.xml` to generate a different hash but the cache is still hit. I think there is a configuration issue somewhere but don't know where.

**Comment by dmitry-shibanov** [comment] 2021-09-03 08:53
Hello @gdrouet. Thank you for your report. Could you please provide public repository to reproduce the issue ?

**Comment by gdrouet** [comment] 2021-09-03 10:46
I'm not able to reproduce the issue.

My cache is actually empty and I don't know why:

```
Cache Size: ~0 MB (22 B)
```

In the post action, the cache is not updated with previsouly downloaded dependencies:

```
Cache hit occurred on the primary key setup-java-Linux-maven-fbf1af4967939d8ef8fafe80343f1668b998728c9bbccf0a0df4306bb69db445, not saving cache.
```

**Comment by dmitry-shibanov** [comment] 2021-09-03 11:00
Hello @gdrouet. It looks like this is an expected behaviour. The setup-java action has restore-keys, that is why you get the previous cache back. The action saves new cache if the pom.xml file is updated, but initially it restores the previous one. 
New builds run on the clean machine, that is why cache does not persist on it. Cache is restored from the faster azure storage during the build to provide dependencies. 

Did you install dependencies for new project ? It looks like you didn't install dependencies, that is why the cache archive is empty.

**Comment by gdrouet** [comment] 2021-09-06 08:47
I solved the issue on my private repository by upgrading a dependency.
In the post action, the cache has been updated with all downloaded depdendencies.
I don't understand why the first time I executed it an empty cache was sanved because maven actually downloaded dependencies.

Can this occur if the cache was not initially activated?

Or maybe I fixed something at a moment that has this side effect, like configuring a different local repository directory for maven...

Anyway having an option to force the cache to be cleared would be handy.

**Comment by dmitry-shibanov** [comment] 2021-09-06 16:03
Hello @gdrouet. Thank you for your response. I don't think it's related to initial cache activation. I suppose, this is an issue with initial project configuration. Possibly you had problems with downloading during the first caching, that is why no dependencies did not exist in the cache directory.  The action saved an empty directory. The action could resave all dependencies when the project configuration was fixed and saving of cache was triggered by pom.xml hash update.

For now I'm closing the issue.

**Closed by dmitry-shibanov** 2021-09-06 16:03 UTC
Labels: bug
