### ISSUE TITLE
Suddenly the step is extremely slow?

### ISSUE THREAD

**Issue by mydea** [actions/setup-java#109] opened 2020-10-14 10:43 UTC
Since a bit more than an hour, suddenly this action became extremely slow - it takes 5-10 minutes to run.

We have multiple workflows which look like this:

```yml
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 6    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "11"
          architecture: "x64"
```

Which now time out because the "Setup Java" step takes too long, and is aborted:

```
Run actions/setup-java@v1
  with:
    java-version: 11
    architecture: x64
    java-package: jdk
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
Error: The operation was canceled.
```

With debugging enabled, I get this output:

```
Run actions/setup-java@v1
##[debug]isExplicit: 
##[debug]explicit? false
##[debug]evaluating 0 versions
##[debug]match not found
##[debug]Downloading JDK from Azul
##[debug]Searching for files with extension: -linux_x64.tar.gz
##[debug]Downloading https://static.azul.com/zulu/bin/zulu11.41.23-ca-jdk11.0.8-linux_x64.tar.gz
##[debug]Downloading /home/runner/work/_temp/396c3e9f-c908-4376-bc75-60add47a4e50
##[debug]Re-evaluate condition on job cancellation for step: 'Setup Java'.
```

**Comment by tonsky** [comment] 2020-10-14 10:45
Same here https://github.com/JetBrains/skija/actions/runs/306292216

**Comment by orestis** [comment] 2020-10-14 11:23
Same, sometimes it fails outright. Cancelling the workflow and re-starting seems to resolve though.

**Comment by mydea** [comment] 2020-10-14 12:14
Seems to be working again for me!

**Comment by dmitry-shibanov** [comment] 2021-01-14 08:43
Hello, everyone. Have you faced up with this issue recently ?

**Comment by dmitry-shibanov** [comment] 2021-02-03 15:13
Hello everyone, I'm closing the issue since it's not reproducible for now. If you have any concerns of questions feel free to reopen the issue.

**Closed by dmitry-shibanov** 2021-02-03 15:13 UTC
Labels: bug
