### ISSUE TITLE
‘actions/setup-java@v1’ removes everything from $PATH 

### ISSUE THREAD

**Issue by cheemcheem** [actions/setup-java#76] opened 2020-06-14 20:56 UTC
Hello,

I was advised to post my issue here from my GitHub Support Community [post](https://github.community/t/actions-setup-java-v1-removes-everything-from-path/118044).

I've had a lot of weird issues at each stage of my pipeline and all of them seemed to have been resolved by setting the `$PATH` variable to `/bin` etc within the step or by hard coding `/bin/chmod` and `/bin/ssh` rather than using `chmod` and `ssh` for example.

I have tracked down the issue to the `actions/setup-java@v1` step replacing the contents of `$PATH` with the path of the JDK.

I call it like this:

```
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13
```
 
Before that step, `echo $PATH` outputs: `/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin`

Whereas after that step, `echo $PATH` outputs: 
`/opt/hostedtoolcache/jdk/13.0.3/x64/bin:***`

Hope this helps and let me know if you need anymore information!

The workflow file that reproduces this is [here](https://github.com/cheemcheem/card-games/blob/cc4fdd51fcafe9b441f1a0b46c75793ba15fa8d4/.github/workflows/main.yml).

Thank you,
Kathan

**Comment by SayakMukhopadhyay** [comment] 2020-10-29 09:12
I am planning to use this action and was wondering if this is still an issue?

**Comment by dmitry-shibanov** [comment] 2021-01-14 09:27
Hello everyone. I tested example above and PATH is present after setup-java action was completed. Is it still an issue for you ?

**Comment by dmitry-shibanov** [comment] 2021-02-03 15:14
Hello @cheemcheem. Just a gentle ping.

**Comment by dmitry-shibanov** [comment] 2021-02-09 07:13
Hello everyone, I'm closing the issue since it's not reproducible. If you have any concerns feel free to reopen the issue.

**Closed by dmitry-shibanov** 2021-02-09 07:13 UTC
Labels: bug
