### ISSUE TITLE
Make distribution default to zulu when not defined

### ISSUE THREAD

**Issue by Andre601** [actions/setup-java#173] opened 2021-04-26 15:35 UTC
**Description:**
If you update setup-java from a version before 2.0.0 through something like Dependabot could it happen, that on merge the action is triggered and fails because of the missing distribution field.
This can be frustrating because not everyone wants to have failing builds due to such an update.

My feature request is about making the distribution field an optional one that would default to `zulu` when not defined. This would allow to keep existing workflows running without causing unwanted failing builds.

**Justification:**
As mentioned before would updating through methods such as Dependabot cause existing workflow runs, which f.e. run on push, to fail because of the missing field, which is something that can be avoided by the above method.

**Are you willing to submit a PR?**

I unfortunately don't have the knowledge to provide my contributions towards this project.

**Comment by dmitry-shibanov** [comment] 2021-04-27 09:08
Hello @Andre601, thank you for report. Based on [ADR](https://github.com/actions/setup-java/blob/main/docs/adrs/0000-v2-setup-java.md#new-input) we're not planning to make distribution field default to zulu. I'm closing the issue as a duplicate of https://github.com/actions/setup-java/issues/154

**Closed by dmitry-shibanov** 2021-04-27 09:08 UTC
Labels: feature request, needs triage
