### ISSUE TITLE
Cache `/root/.m2/repository`

### ISSUE THREAD

**Issue by tristan957** [actions/setup-java#356] opened 2022-07-15 02:28 UTC
**Description:**
I use containers (Ubuntu, Fedora, Almalinux) in GitHub Actions. In my workflows, I am using this action. In the "Post Setup Java" step, I see a warning about a path validation error.

What I have discovered is that the Maven local repository path by default is `/root/.m2/repository`, so `~/.m2/repository` doesn't exist.

**Justification:**
This is a very hard issue to discover, and since this path seems to the default on many images, or at least the ones I am using, it should be cached in addition to the usual `~/.m2/repository`.

https://github.com/actions/cache/issues/814

**Are you willing to submit a PR?**
Potentially.

Alternatively, allow us as users to configure the cache path ourselves.

**Comment by dsame** [comment] 2022-07-15 10:29
hello @tristan957 
Thanks for sharing your use case, as a quick solution there's an action for custom caching https://github.com/actions/cache
Meanwhile we will investigate the issue and make a  decision about adding the directory to the automatic cache.

**Comment by tristan957** [comment] 2022-07-15 12:07
Yep, I think I'll probably implement that today now that I know what the problem is. Thanks!

**Comment by dsame** [comment] 2022-07-15 15:19
@tristan957 from this  "path by default is /root/.m2/repository" i could suggest there's `sudo` or `su` call somewhere.

**Comment by tristan957** [comment] 2022-07-15 15:24
That would make sense. Here is a minimal GitHub Actions file that can recreate the path.

```yaml
jobs:
  fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:36

    steps:
      - run: |
          dnf install maven
          mvn help:evaluate -Dexpression=settings.localRepository | grep 'm2/repository'
```

Notice how you don't need `sudo` for `dnf`. Seems like GitHub drops you in as a privileged user within the container.

**Comment by tristan957** [comment] 2022-07-27 17:20
Makes sense. Thanks for your continued work on this issue.

**Comment by nikola-jokic** [comment] 2022-08-09 14:16
Hey everyone,

I will try to provide more context to why is this happening. 

When starting a job within a container, the runner will add system volume mounts. The volume mount interesting for this issue is `/github/home` which will be mapped to the `PATH_TO_YOUR_RUNNER_WORK/_temp/_github_home`. It is that directory that is going to be used as a HOME, and can ensure that `$HOME` directory exists regardless of the container you are using. 

But on the other hand, this introduces problems when users or scripts rely on the predefined $HOME variable that they expect to be set by the container. The issue is especially tricky when you create a [docker container action](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action), with the `USER` directive env `HOME` env set.

The reason the workaround works, is that the env field overwrites environment in context of this step, so when you invoke a command, it will use envs specified for that step, which is great for this particular use-case.

In situations where you want to customize containers used by jobs, and you are using self-hosted runners, you can use [container hooks](https://docs.github.com/en/actions/hosting-your-own-runners/customizing-the-containers-used-by-jobs). 

We are aware of this issue, and we are looking at ways to solve it without breaking existing workflows that rely on current behaviour.

I hope this is helpful, and please, let me know if you have any questions regarding this :relaxed:

**Comment by dsame** [comment] 2022-08-22 06:46
@nikola-jokic thanks for your input. Can we close this issue as not related to the action and create another one in this repo https://github.com/actions/runner ?

**Comment by dsame** [comment] 2022-08-23 07:17
@tristan957 i am closing the issue because of the problem relates to https://github.com/actions/runner repository and  there's no activity for 2 weeks. Please feel free to create the issue in this project in case of any problem.

**Closed by dsame** 2022-08-23 07:17 UTC
Labels: feature request
