### ISSUE TITLE
setup-java action failes on self-hosted runner with Error: aborted

### ISSUE THREAD

**Issue by dzenansoftic** [actions/setup-java#695] opened 2024-10-14 13:54 UTC
**Description:**
When trying to download java 21 (distribution microsoft) the step failes after some retries, because it aborted without any error message or explanation. This is on a self-hosted runner. We have multiple workflows running at the same time on different self-hosted runners. 

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Repro steps:**  
run the setup-java action in a self-hosted runner

**Expected behavior:**
Successful download

**Actual behavior:**
Action failes and only Error shown is aborted

![image](https://github.com/user-attachments/assets/bdca3146-fd3b-4828-bacf-933280660ff3)

**Comment by d3r3kk** [comment] 2024-10-15 15:11
We cannot reproduce this issue from our network. Can you please provide further details by adding debug switches to the download task, or perhaps doing a traceroute from the agent prior to downloading (also, does your download agent deal with redirects well?)? Have you tried to do this manually from your own workstation? What happens if you try and download a different version (21.0.3 for instance)?

**Comment by aparnajyothi-y** [comment] 2024-10-15 16:00
Hello @dzenansoftic, Thank you for creating this issue. The error message you encountered seems to be related to a server downtime.

We have run the same workflow on our end, and the setup job completed successfully. Please refer to the attached screenshots for your reference.
<img width="1415" alt="Screenshot 2024-10-15 at 6 42 00 PM" src="https://github.com/user-attachments/assets/6c55e834-696d-41b8-93c7-ed6b0bbcc4a1">

Could you please re-trigger the workflow on your end and confirm if the issue persists?

Feel free to reach out if you need any further clarifications.

**Comment by stefanschulte** [comment] 2024-10-16 17:16
Just to provide some more context: I've seen the same error twice in the last 2 days, although my workflows run on github hosted default ubuntu runners.

Same error message. Download then again works fine when just re-running the same workflow again.
![image](https://github.com/user-attachments/assets/b89141a7-3e3a-4d61-a6bb-213b86a48493)

**Comment by aparnajyothi-y** [comment] 2024-10-29 13:00
Hello @dzenansoftic, please let us know if the re-trigger resolved the issue. If you have any further concerns or questions, feel free to reach out.

**Comment by aparnajyothi-y** [comment] 2024-11-05 11:46
Hello @dzenansoftic, gently following up to see if re-triggering the process has resolved the issue. If you have any further questions or concerns, please don’t hesitate to reach out.

**Comment by aparnajyothi-y** [comment] 2024-11-12 14:02
Hello @dzenansoftic  , We are proceeding to close this issue after two reminders as we didn't hear anything from you for a long time. 
@stefanschulte As explained above, This issue encountered seems to be related to a server downtime.
Please feel free to reach us in case of any further concerns to reopen this issue.

**Closed by aparnajyothi-y** 2024-11-12 14:02 UTC
Labels: bug
