### ISSUE TITLE
Add support for Oracle OpenJDK binaries

### ISSUE THREAD

**Issue by giltene** [actions/setup-java#69] opened 2020-05-28 00:47 UTC
With work being done towards adding additional binary distributions of OpenJDK as options (likely under the "distro" option, see e.g. https://github.com/actions/setup-java/pull/67), it would be useful to include the Oracle OpenJDK binaries among the distro options

**Comment by sormuras** [comment] 2020-06-28 20:07
In the meanwhile, I published https://github.com/sormuras/download-jdk -- which downloads a JDK from https://jdk.java.net that is consumable by `actions/setup-java` as two-step installation routine.

**Comment by sormuras** [comment] 2020-10-12 06:25
FYI, I updated [sormuras/download-jdk](https://github.com/marketplace/actions/download-jdk)`@v1` to version 1.1:

- Supports Linux, Mac OS, and Windows
- Supports Early-Access builds of top-level projects, like Loom, Panama, or Valhalla
- Supports archived (EOL!) builds

**Comment by rahim873** [comment] 2020-10-12 19:13
Google
andriod

Pada Isn, 12 Okt 2020 14:25 Christian Stein <notifications@github.com>
menulis:

**Comment by xor-freenet** [comment] 2022-03-09 13:01
Good reason to fix this:
Consider how large a discussion about which of the non-Oracle JDKs to use can grow: https://news.ycombinator.com/item?id=28820601
Not everybody has the time to dive into that much complexity just to run their code :)

**Comment by xor-freenet** [comment] 2022-03-14 21:45
@carimura 
Thanks for the effort! :)

Actions can have very high level of access to a repository and thus a high security impact.  
I would therefore be reluctant to run any Actions which are not part of the official ones of GitHub.

Thus please do indeed ship your code as a PR to this official repository :)

**Comment by berezovskyi** [comment] 2022-03-23 13:36
@xor-freenet given that they rewrote all the TS code in Java from scratch, it may be a bit challenging...

**Comment by slawekjaranowski** [comment] 2022-03-28 12:45
I'm also for merging `oracle-actions/setup-java` into `actions/setup-java`

With two actions using matrix for jdk is difficult ....

**Comment by delabassee** [comment] 2022-03-28 13:27
@slawekjaranowski @berezovskyi https://inside.java/2022/03/11/setup-java/ explains why we needed a separate action

**Comment by berezovskyi** [comment] 2022-03-28 13:34
@delabassee I buy all the arguments except why a rewrite from TypeScript was needed. TypeScript is not my favourite language but I think all of the changes Oracle team needed could have been implemented as a PR. Anyway, I am awaiting native support for #68 more eagerly as NFTC only vaguely permits "running the Program for Your own personal use or _internal_ business operations".

**Comment by fniephaus** [comment] 2022-11-04 15:40
Hi all, I've opened #401 which adds support for Oracle JDK to this action.

**Comment by sormuras** [comment] 2022-11-10 07:35
Thanks @fniephaus - would be awesome to get an official review of your PR in order to make developers live easier, especially for those using this action in a matrix setup.

**Comment by brcrista** [comment] 2022-12-05 16:55
Thanks for the PR @fniephaus.  Unfortunately, we historically haven't been able to support Oracle JDK and I believe we are still in that state.

As a result, we had to roll back the v3.7 release for `setup-java` which included this change.  That means:
- Workflows that are referencing `actions/setup-java@v3.7` will fail to resolve the action and will need to go back to `actions/setup-java@v3.6`.
- Workflows that are referencing `actions/setup-java@v3` should not be impacted unless they are using`distribution: oracle`.

I apologize for the churn that this creates.  I wanted to roll back the change as quickly as possible to minimize the number of workflows and `setup-java` releases that would be affected.  I also apologize for not catching the issue sooner.  We're working on adding some PR and Issue templates specifically for new Java distributions to make sure those changes get reviewed appropriately.

**Comment by berezovskyi** [comment] 2022-12-05 21:23
> Unfortunately, we historically haven't been able to support Oracle JDK and I believe we are still in that state.

Do I understand you correctly that the issue is not technical?

**Comment by dmitry-shibanov** [comment] 2023-02-07 17:29
Hello everyone. We had discussions with Oracle teams and confirmed that we can add support for Oracle OpenJDK. We've released a new [version](https://github.com/actions/setup-java/releases/tag/v3.10.0) of the action with support of Oracle OpenJDK. We are sorry for the confusion.

**Comment by jsoref** [comment] 2023-03-05 18:14
@dmitry-shibanov: is there a reason you didn't close this ticket?

**Comment by dmitry-shibanov** [comment] 2023-03-06 00:12
Hello @jsoref. Sorry for the delay in closing the issue. For now I'm going to close the issue because the new version [3.10.0](https://github.com/actions/setup-java/releases/tag/v3.10.0) with support of Oracle OpenJDK was released and the major tag was updated.

**Closed by dmitry-shibanov** 2023-03-06 00:12 UTC
Labels: v2 setup-java, feature request

**Comment by mobeicanyue** [comment] 2023-12-18 08:01
Thanks for your guys generous works. And one question, I looking for v3.10.0, but I find that it's Oracle jdk, and seems not Oracle openjdk, why not support Oracle openjdk? I think it's not technique trouble, any question about License?

**Comment by IvanZosimov** [comment] 2023-12-19 09:51
Hi, @mobeicanyue 👋 Thanks for the question, actually we have an open [feature request](https://github.com/actions/setup-java/issues/492) related to adding OpenJDK. As soon as we got license-wise approve, the implementation process can be started.

**Comment by mobeicanyue** [comment] 2023-12-19 19:25
> Hi, @mobeicanyue 👋 Thanks for the question, actually we have an open [feature request](https://github.com/actions/setup-java/issues/492) related to adding OpenJDK. As soon as we got license-wise approval, the implementation process can be started.

Could I learn about the approval progress? I think it's so wired about oracle, they seems put copyright so hard even to open source project.
