### ISSUE TITLE
Not recognizing existing installation of java in toolcache

### ISSUE THREAD

**Issue by sunnyoswalcro** [actions/setup-java#358] opened 2022-07-28 13:44 UTC
**Description:**
+ java distribution - temurin 8.0.302 - is always being downloaded
+ not recognizing existing installation

**Task version:**
v3

**Platform:**
- [ this] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ this] Self-hosted

**Repro steps:**  

ACTION CONFIGURATION
```
- uses: actions/setup-java@v3
  with:
    distribution: 'temurin'
    java-version: '8.0.302'
    cache: 'gradle'
```

DOCKERFILE FOR SELF HOSTED RUNNER
```
FROM summerwind/actions-runner:latest

ARG HELM_VERSION=3.9.0
ENV JAVA_VERSION 8.0.302
ENV URL https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u302-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u302b08.tar.gz
ENV JAVA_HOME /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/${JAVA_VERSION}-8/x64
ENV GRADLE_VERSION=7.3.2 \
	PATH=/opt/gradle/bin:$PATH

RUN sudo apt update -y \
    && curl -fL https://getcli.jfrog.io | sudo bash \
    && sudo chmod +x jfrog \
    && sudo mkdir -p  /usr/local/bin/ \
    && sudo mv ./jfrog /usr/local/bin/

SHELL ["/bin/bash", "-c"] 

RUN sudo wget --quiet "${URL}" && \
	sudo mkdir -p ${JAVA_HOME} && \
	sudo tar -xzf OpenJDK8U-jdk_x64_linux_hotspot_8u302b08.tar.gz --strip-components=1 -C ${JAVA_HOME} && \
	sudo rm OpenJDK8U-jdk_x64_linux_hotspot_8u302b08.tar.gz && \
	if [[ "$JAVA_VERSION" == *"0.0"* ]]; then sudo ln -s ${JAVA_HOME} /usr/local/jdk-8; fi && \
	sudo ln -s ${JAVA_HOME}/bin/java /usr/bin/java && \
	sudo ln -s ${JAVA_HOME}/bin/javac /usr/bin/javac && \
	sudo ln -s ${JAVA_HOME}/bin/javaws /usr/bin/javaws && \
	# Install packages to help with legacy image migration
	sudo apt-get update && sudo apt-get install -y \
		fontconfig \
	&& \
	sudo rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

```

**Expected behavior:**
Resolved Java 8.0.302+8 from tool-cache

**Actual behavior:**
TRUNCATED
```
Run actions/setup-java@v3
  with:
    distribution: temurin
    java-version: 8.0.302
    cache: gradle
    java-package: jdk
    architecture: x64
    check-latest: false
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true
    job-status: success
  env:
    FORCE_RESET_DEPENDENCY_RESOLVE_DETAILS: true
Trying to resolve the latest version from remote
Resolved latest version as 8.0.302+8
Trying to download...
Downloading Java 8.0.302+8 (Temurin-Hotspot) from https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u302-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u302b08.tar.gz ...
Extracting Java archive...
/usr/bin/tar xz --warning=no-unknown-keyword -C /runner/_work/_temp/1bf06eb2-bd94-4e20-a2fc-5218d73974a1 -f /runner/_work/_temp/7030f970-13e8-446e-afdc-8ddfdc6d2a77
Error: Command failed: rm -rf "/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.2-8/x64"
rm: cannot remove '/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.302-8/x64/ASSEMBLY_EXCEPTION': Permission denied
rm: cannot remove '/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.302-8/x64/LICENSE': Permission denied
rm: cannot remove '/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.302-8/x64/NOTICE': Permission denied
rm: cannot remove '/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.302-8/x64/THIRD_PARTY_README': Permission denied
rm: cannot remove '/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.302-8/x64/bin/appletviewer': Permission denied
```

**Comment by marko-zivic-93** [comment] 2022-07-28 13:48
Hello @sunnyoswalcro 
We will investigate this issue and get back to you as soon as possible with some feedback. :)

**Comment by sunnyoswalcro** [comment] 2022-07-28 13:52
i had tried figuring out myself by going through the code but no luck. May be adding some logs in `findInToolcache` would help
https://raw.githubusercontent.com/actions/setup-java/main/dist/setup/index.js

**Comment by dmitry-shibanov** [comment] 2022-07-28 15:17
Hello @sunnyoswalcro. I think it's an expected behaviour because the actions uses [findAllVersions](https://github.com/actions/toolkit/blob/01e1ff7bc04e1c57c980a0d1530478a5b60cf812/packages/tool-cache/src/tool-cache.ts#L544) to get all versions and it relies on [complete file](https://github.com/actions/toolkit/blob/01e1ff7bc04e1c57c980a0d1530478a5b60cf812/packages/tool-cache/src/tool-cache.ts#L555) which the installed java from wget does not have.

**Comment by dmitry-shibanov** [comment] 2022-08-04 15:01
Hello @sunnyoswalcro. For now I'm going to close the issue.

**Closed by dmitry-shibanov** 2022-08-04 15:01 UTC
Labels: bug
