### ISSUE TITLE
Gradle cache increases by 400 MB every time updating Gradle wrapper version

### ISSUE THREAD

**Issue by DevCharly** [actions/setup-java#269] opened 2022-01-04 17:39 UTC
**Description:**
When updating the Gradle wrapper to a new version (changed `gradle-wrapper.properties`), then
1. setup-java@v2 first restores the gradle cache from **previous run** (why??)
2. new Gradle version is downloaded and build
3. then setup-java@v2 creates a new cache file (~800 MB) which is about 400 MB larger than before because it contains two Gradle versions

Changing Gradle wrapper version again increases the cache file size by 400 MB to 1200 MB, and so on...

Here is a run where it happened: https://github.com/JFormDesigner/FlatLaf/runs/4705134891

In "Setup Java 17" the outdated cache is restored (https://github.com/JFormDesigner/FlatLaf/runs/4705134891#step:4:35):
~~~
Cache Size: ~425 MB (445413982 B)
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/19b74bcf-0264-4065-b1ef-448c93c2d4fc/cache.tzst -P -C /home/runner/work/FlatLaf/FlatLaf
Cache restored successfully
Cache restored from key: setup-java-Linux-gradle-707ed6f8250ea8ec2ee660640962308e354fe354d36338715ef1bcab4fcc837f
~~~

In "Post Setup Java 17" a new cache with ~836 MB is created (https://github.com/JFormDesigner/FlatLaf/runs/4705134891#step:11:5):
~~~
Cache Size: ~836 MB (876885346 B)
Cache saved successfully
Cache saved with the key: setup-java-Linux-gradle-af7e537f7a03362010edc6596ab7fba05bdfb901982028cbd2d21e5291cd932d
~~~

Note the different hash keys in the cache file names!

**Task version:**
actions/checkout@v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
See above description.

**Expected behavior:**
When changing `gradle-wrapper.properties` (or `build.gradle`), then the cache should be not restored.

**Actual behavior:**
Cache is restored even if `gradle-wrapper.properties` (or `build.gradle`) changed, which increases the size of the cache file by aboud 400 MB every time a new Gradle wrapper version is used.

**Comment by dmitry-shibanov** [comment] 2022-01-06 11:45
Hello @DevCharly. Thank you for your report. We'll investigate the issue.

**Comment by schuenadel** [comment] 2022-01-13 15:22
> Expected behavior:
> When changing gradle-wrapper.properties (or build.gradle), then the cache should be not restored.

I think so too, especially if there is not other cache eviction happening than [this](https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy), which would mean it grows "forever" (if you access it once a week).
My suggestion would be to remove the `restoreKeys` (3rd) parameter in [here](https://github.com/actions/setup-java/blob/a12e082d834968c1847f782019214fadd20719f6/src/cache.ts#L75-L77), so that whenever the cache key changes you start with a completely clean cache. But on the other hand that means for every change all(!) dependencies are downloaded again.

**Comment by DevCharly** [comment] 2022-01-13 15:43
Shouldn't the cache ID calculated from the (gradle) files in working directory, which was previously checked out from git?

Currently it seems that the cache ID from the previous run is used,
which always restores cache from previous run.
Seems to be useless because the cache never becomes dirty...

> But on the other hand that means for every change all(!) dependencies are downloaded again.

Isn't this the expected behavior?
The cache does not know what is still needed and what can be removed
when you change the version of a dependency or remove a dependency.

**Comment by schuenadel** [comment] 2022-01-14 09:47
> Shouldn't the cache ID calculated from the (gradle) files in working directory, which was previously checked out from git?

It is, but when no cache with that id is found, like when you run the first time with a new dependency configuration, it falls back to a cache from a previous run. That fallback is defined with the `restoreKeys` parameter, which I suggested above to remove.

> > But on the other hand that means for every change all(!) dependencies are downloaded again.
> 
> Isn't this the expected behavior?

One could argue that when you change only one small dependency out of many others it may be more efficient to keep 2 versions of that in the cache instead of downloading all again. But as you said, when the cache **never** becomes dirty I would also prefer to start over with a completely empty cache whenever something changes.

**Comment by schuenadel** [comment] 2022-01-25 14:44
I put my suggestion into a PR [here](https://github.com/actions/setup-java/pull/285) to make it more clear what I mean to prevent this problem.

**Comment by devminded** [comment] 2022-01-29 19:36
After a quick scan through the code it looks like it creates a single cache-key and includes both build/dependency caches and wrapper cache in said key.

Would it not make more sense to have two separate caches/keys with different restore policies? And also, when saving the build/dependency caches we should be able to exclude files older than a configurable number of hours/days. Not sure how that is handled today though. This way we can have the best of both worlds.

Same issue will need to be solved within #245 .

**Comment by mandrachek** [comment] 2022-04-14 14:11
Is this why my cache is now 3GB in size, actions/setup-java@v3 takes ~12 minutes to run (downloading and restoring the cache), and why my post run setup-java action is failing?

Is there some way to purge the cache and get a clean slate at least for the time being?

**Comment by fl250144** [comment] 2022-04-28 17:21
> Is this why my cache is now 3GB in size, actions/setup-java@v3 takes ~12 minutes to run (downloading and restoring the cache), and why my post run setup-java action is failing?
> 
> Is there some way to purge the cache and get a clean slate at least for the time being?

i have the same question...

**Comment by schuenadel** [comment] 2022-04-29 09:25
@mandrachek and @fl250144 

> Is this why my cache is now 3GB in size, actions/setup-java@v3 takes ~12 minutes to run

I don't know your setup, but the cache filling up over time sounds like you have this issue.

> Is there some way to purge the cache and get a clean slate at least for the time being?

One thing you could do for now is to not use the built-in cache of `actions/setup-java` but instead use `actions/cache` directly. There you can define cache keys to fit your needs. Maybe something time-related, like week number to make sure the cache is dropped at least once per week. Of course this is not ideal, but maybe helps you for now.

**Comment by mandrachek** [comment] 2022-04-29 10:16
@schuenadel - that's exactly the approach I wound up taking.

@fl250144 - here's what I used instead of the built-in cache:

```yaml
  # This works around an issue in setup-java which allows the dependency cache to grow each time the gradle wrapper is upgraded 
 ​      - ​name​: ​Cache Gradle Wrapper and Dependencies 
 ​        ​uses​: ​actions/cache@v3 
 ​        ​with​: 
 ​          ​path​: ​| 
 ​            ~/.gradle/caches 
 ​            ~/.gradle/wrapper 
 ​          ​key​: ​${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle/wrapper/gradle-wrapper.properties') }}
```

It adds the hash of gradle-wrapper.properties, so when the gradle version is updated, the cache is rebuilt.

**Comment by bishal-pdMSFT** [comment] 2022-06-30 09:23
> Is there some way to purge the cache and get a clean slate at least for the time being?

You can now use REST APIs to purge a cache based on key or id (id can be fetched using the another API which lists caches)
[Delete caches by key ](https://docs.github.com/en/rest/actions/cache#delete-github-actions-caches-for-a-repository-using-a-cache-key)
[Delete specific cache by Id](https://docs.github.com/en/rest/actions/cache#delete-a-github-actions-cache-for-a-repository-using-a-cache-id)
[List/filter caches](https://docs.github.com/en/rest/actions/cache#list-github-actions-caches-for-a-repository) to get cache Id

**Comment by bishal-pdMSFT** [comment] 2022-06-30 09:47
>I think so too, especially if there is not other cache eviction happening than [this](https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy), which would mean it grows "forever" (if you access it once a week).

There is a nuance. If there are more recently used caches in a repo and the total size is more than 10 GB even a weekly accessed cache will get evicted. Essentially the eviction logic find caches which need to be purged to bring total cache usage size to 10GB and it purges the ones which are oldest till the size goal is met.

**Comment by dsame** [comment] 2022-07-11 07:15
Hello @DevCharly 

It seems i found the root cause and can suggest at least the workaround which can be called a solution as well.

The origin of the problem is the logic of `actions/cache` restore: it DO restores the most recent cache even if the cache-key was not found.

As a result,   despite `gradle/wrapper/gradle-wrapper.properties` has been changed to the new version of the gradle and cash-key has changed the old cache with the previous gradle still restored and new gradle jar with the dependencies files does not replace the old one, but is added to the `.gradle/cache` folder.

Thus, to resolve the problem it is necessary either 1) changes the logic of `actions/setup` or 2) add a cleaning step to `actions/java-setup`

My opinion is: neither of above can be applied because of 1) is breaking change and 2) is not flexible enough

I'd suggest to add the project specific step to the pipeline, something like:

```
        - uses: actions/setup-java@v3
          id: setup-java
          with:
            java-version: '8'
            distribution: 'zulu'

        - name: Force clear gradle cache
          if: steps.setup-java.outputs.cache-hit != 'true'
          run: rm -r ~/.gradle/caches
```

This way completely solves the issue but leaves an ability to fine tuning the specific build. 
Any thoughts?

**Comment by dsame** [comment] 2022-07-16 09:48
> I put my suggestion into a PR [here](https://github.com/actions/setup-java/pull/285) to make it more clear what I mean to prevent this problem.

The PR is merged now, and the workaround i've suggested in the [reply](https://github.com/actions/setup-java/issues/269#issuecomment-1180048592) will become unnecessary on next release.

**Comment by dsame** [comment] 2022-09-12 06:31
The issue is to be closed due to the merged PR.

**Closed by dsame** 2022-09-12 06:31 UTC
Labels: bug

**Comment by b-heimann-senacor** [comment] 2024-09-04 15:53
I use Maven without a wrapper and I don't have a problem with increasing cache size. Since actions/setup-java no longer restores the old cache when the pom.xml file has changed, it needs to download all dependencies anew with every small configuration change in the pom.xml file, and it takes 20 minutes each time for my project. 
Why wasn't this problem solved specifically for Gradle?
