### ISSUE TITLE
Add Alibaba Dragonwell JDK

### ISSUE THREAD

**Issue by Accelerator1996** [actions/setup-java#443] opened 2023-01-12 07:56 UTC
**Description:**
We want to add Alibaba Dragonwell JDK into setup-java so that users can use it conveniently.

**Comment by panticmilos** [comment] 2023-01-12 09:14
hi, @Accelerator1996 thank you for submitting the report, we will take a look at it.

**Comment by IvanZosimov** [comment] 2023-07-06 08:52
Hi, @Accelerator1996 👋 I'm closing this issue as a duplicate of the https://github.com/actions/setup-java/issues/71.. You can keep track of the issue there.

**Closed by IvanZosimov** 2023-07-06 08:52 UTC
Labels: duplicate, feature request

**Comment by Accelerator1996** [comment] 2023-07-06 09:08
> Hi, @Accelerator1996 👋 I'm closing this issue as a duplicate of the #71. You can keep track of the issue there.

Thank you very much
