### ISSUE TITLE
Failed to setup latest java 18 from jdk.java.net

### ISSUE THREAD

**Issue by joel-costigliola** [actions/setup-java#361] opened 2022-08-08 10:51 UTC
**Description:**

Failed to setup latest java 18 from jdk.java.net in https://github.com/assertj/assertj/runs/7723702038?check_suite_focus=true

**Task version:**

actions/setup-java@v3

**Platform:**
- [x] Ubuntu (not 100% sure it is ubuntu but it's linux)
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

https://github.com/assertj/assertj/runs/7723702038?check_suite_focus=true

**Expected behavior:**

a successful setup as the one for java 19 in this same build: https://github.com/assertj/assertj/runs/7723702183?check_suite_focus=true

**Actual behavior:**

Failure with the following error:
```
Run actions/setup-java@v3
  with:
    java-version: -457401206
    distribution: jdkfile
    jdkFile: /home/runner/.oracle-actions/setup-java/e4bc9c8a/openjdk-18.0.2_linux-x64_bin.tar.gz
    java-package: jdk
    architecture: x64
    check-latest: false
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true
    job-status: success
Error: The string '-457401206' is not valid SemVer notation for a Java version. Please check README file for code snippets and more detailed information
```

**Comment by dmitry-shibanov** [comment] 2022-08-08 11:47
Hello @joel-costigliola. Thank you for your report. If I understand correctly you're using composite action to utilize actions/setup-java. I think it an expected behaviour because [the wrong version](https://github.com/assertj/assertj/runs/7723702038?check_suite_focus=true#step:3:29) (non SemVer notation) was passed.

**Comment by scordio** [comment] 2022-08-08 11:53
We actually use [`oracle-actions/setup-java`](https://github.com/oracle-actions/setup-java) which uses `actions/setup-java` under the hood, so maybe the root cause is there. I'll raise a corresponding issue with them.

**Comment by scordio** [comment] 2022-08-08 12:44
Triggering again the same job [worked](https://github.com/assertj/assertj/runs/7725378121), I guess it was a temporary issue.

I anyway raised oracle-actions/setup-java#39 but I guess this issue could be closed.

**Comment by dmitry-shibanov** [comment] 2022-08-08 14:05
Hello @scordio. Thank you for your response. For now I'm going to close the issue.

**Closed by dmitry-shibanov** 2022-08-08 14:05 UTC
Labels: bug
