### ISSUE TITLE
Add support for multiple server credentials in Maven

### ISSUE THREAD

**Issue by reckart** [actions/setup-java#427] opened 2022-12-09 09:46 UTC
**Description:**
Currently, it is possible to generate a `settings.xml` that contains exactly one server section with GH credentials.
Instead, it should be possible to generate multiple server sections with GH credentials.

**Justification:**
When a project depends on multiple other projects that each use GitHub packages, then it needs to include a `repository` declaration for each of these. However, these repository declarations cannot all use the same ID `github` because the IDs must be unique. So in order to be able to draw in dependencies from multiple GitHub packages repositories, it must be possible to generate multiple server sections, one for each of the GitHub packages repositories.

**Comment by marko-zivic-93** [comment] 2022-12-12 08:12
Hello @reckart 
Thank you for bringing this up! We will investigate this issue and come back to you as soon as we have some useful information! 😃

**Comment by IvanZosimov** [comment] 2023-03-21 11:18
Hi, @reckart 👋 Sorry, but this feature request is a duplicate of https://github.com/actions/setup-java/issues/85. I'm going to close your feature request now, meanwhile you can track https://github.com/actions/setup-java/issues/85.

**Closed by IvanZosimov** 2023-03-21 11:18 UTC
Labels: feature request
