### ISSUE TITLE
Failed to delete key

### ISSUE THREAD

**Issue by somayaj** [actions/setup-java#251] opened 2021-11-18 00:19 UTC
**Description:**
Post job cleanup.
Removing private key from keychain
Error: Failed to remove private key due to: The process '/usr/bin/gpg' failed with exit code 2
Cache hit occurred on the primary key setup-java-Linux-maven-84bd8427f2439782d3b8d076cd2b5fea27efa2d8115f45ec17e053d67afe1cb3, not saving cache.

**Task version:**
@v2.3.1

**Platform:**
- [ ] Ubuntu
- [X] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Repro steps:**  
use the git action step to run the java 8 job
**Expected behavior:**
graceful exit and deletion of the gpg key.

**Actual behavior:**
failure, as depicted above.

**Comment by dmitry-shibanov** [comment] 2021-11-18 07:06
Hello @somayaj. Thank you for your report. Could you please provide public repository or minimum repro steps to reproduce the issue ?

**Comment by somayaj** [comment] 2021-11-18 13:10
@dmitry-shibanov  i fthis helps, https://github.com/graybytes/module-maven-plugin/blob/main/.github/workflows/maven.yml

**Comment by dmitry-shibanov** [comment] 2021-11-18 13:40
Hello @somayaj. I think it can be related to the `crazy-max/ghaction-import-gpg@v1` action, because both actions remove gpg private keys. Could you please for testing remove this action temporary ?

**Comment by somayaj** [comment] 2021-11-19 20:01
@dmitry-shibanov sure, can do. Is there a action that I can use instead of this to import gpg keys?

**Comment by somayaj** [comment] 2021-11-20 18:48
Ok @dmitry-shibanov remove the crazt-max action and it worked. https://github.com/graybytes/module-maven-plugin/runs/4268678396?check_suite_focus=true. But need a replacement to import gpg keys. Can you advise and also the set-java action should be able to not delete when the keys are already deleted and not available?

**Comment by somayaj** [comment] 2021-11-27 07:01
@dmitry-shibanov please advise on the next steps? is this a bug that's going to be fixed?

**Comment by dmitry-shibanov** [comment] 2021-11-29 11:27
Hello @somayaj. I'm not sure it's really a bug, because we should remove gpg private key fingerprint. The `crazy-max/ghaction-import-gpg@v1` action does the same, that is why If we change their order the build will fail with the same.

**Comment by dmitry-shibanov** [comment] 2021-12-29 12:06
Hello @somayaj, just a gentle ping.

**Comment by somayaj** [comment] 2021-12-29 12:26
Hi, this was taken care of, thank you.

Asha

**Comment by dmitry-shibanov** [comment] 2021-12-29 14:02
Hello @somayaj. Thank you for your response. For now I'm going to close the issue. If you have any concerns feel free to ping us.

**Closed by dmitry-shibanov** 2021-12-29 14:02 UTC
Labels: bug

**Comment by carlosthe19916** [comment] 2022-08-09 09:00
I'm experimenting the same issue today, I've rerun multiple times the same workflow in the past and never failed. However today all builds are failing due to 

```
2022-08-09T07:31:47.4587850Z Post job cleanup.
2022-08-09T07:31:47.6321878Z Removing private key from keychain
2022-08-09T07:31:47.6468455Z Cache hit occurred on the primary key setup-java-Linux-maven-20dfec635c6834cb327074976d0c2dcb80d86aa5898e57d942f4300423af00f6, not saving cache.
2022-08-09T07:31:47.6563675Z Post job cleanup.
```

If it helps this is the link of the build:
https://github.com/windup/windup-pipelines/runs/7742279699?check_suite_focus=true

**Comment by panticmilos** [comment] 2022-08-10 08:28
Hi @carlosthe19916, I saw some changes in your workflow, and that builds are passing now. Is everything resolved for you?

**Comment by carlosthe19916** [comment] 2022-08-10 08:32
Hi @panticmilos thanks for your reply. I have created an independent issue to report my problem https://github.com/actions/setup-java/issues/362 . I have solved my issue but because of the hurry it was easier to stop using the cache embedded in `setup-java` and use `actions/cache@v3`. I have explained the outcome of my small analysis here https://github.com/actions/setup-java/issues/362#issuecomment-1210331034

**Comment by Jbranadev** [comment] 2023-09-03 00:48
Estoy experimentando el mismo problema al tratar de configurar el flujo de publicación de maven.

El error en cuestión es: [publish](https://github.com/Jbranadev/JBSqlUtils/actions/runs/6061304534/job/16446610390#step:11:84)
Failed to remove private key due to: The process '/usr/bin/gpg' failed with exit code 2

y el codigo de la acción lo puede encontrar en: https://github.com/Jbranadev/JBSqlUtils/blob/master/.github/workflows/PublishMaven.yml

Desde ya agradezco su ayuda
