### ISSUE TITLE
Java-version is not specified on self-hosted but ok on github-runner

### ISSUE THREAD

**Issue by bissquit** [actions/setup-java#348] opened 2022-06-29 20:53 UTC
**Description:**
I use the following settings in my workflow:

```
...
jobs:
  job-name:
    runs-on: [self-hosted]
    container:
      image: ubuntu:20.04
...
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          java-package: jdk+fx
          cache: gradle
...
```
It works fine on GitHub-hosted runners but fails on clear Ubuntu 20.04/22.04 installation with error:
```
Error: Input required and not supplied: java-version
```
I'm ready to provide additional debug from worker logs but id doesn't contain useful information. Advice please how get additional debugging information. Maybe there is an option to run action manually inside docker container

**Task version:**
v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Repro steps:**  
1. Install Ubuntu official distribution on Hyper-V virtual machine (check Docker as additional option to be installed)
2. Install runner according to [official article](https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners) and [run as a service](https://docs.github.com/en/actions/hosting-your-own-runners/configuring-the-self-hosted-runner-application-as-a-service).

**Expected behavior:**
Java installed

**Actual behavior:**
Workflow crashed

**Comment by dmitry-shibanov** [comment] 2022-06-29 21:32
Hello @bissquit. Thank you for your report. Could you please try to use the latest major action version (v3)?

**Comment by bissquit** [comment] 2022-06-30 06:54
> Hello @bissquit. Thank you for your report. Could you please try to use the latest major action version (v3)?

Yes, sure but with the same result unfortunately

**Comment by dsame** [comment] 2022-07-01 03:57
Hello @bissquit. 

I was trying to reproduce the problem but without success. 
The flow from the description [works for me](https://github.com/akv-demo/setup-java-test/runs/7143534846?check_suite_focus=true).

For further investigations can you please 
1. provide exact workflow pipeline, may be from some simplified repro - i suspect there's a problem with variable substitution
2. expand `Run actions/setup-java@v3` node in the build log and make sure `java-version` is really passed - i meand this
<img width="590" alt="image" src="https://user-images.githubusercontent.com/245540/176820383-06245d5a-5bfc-4309-804f-082a118d037b.png">
3. change `self-hosted` to `ubuntu-latest` - i should not matter if the build run within container and the build should fail

**Comment by bissquit** [comment] 2022-07-01 06:19
Thank you for your help! I'll provide more debug info later. Possibly I'll try to run action manually inside container

**Comment by bissquit** [comment] 2022-07-11 06:40
Looks like Docker exec command cannot pass all required environment variables.

1. I got the full command from worker log;
2. While action was in running state (approximately 1-2 sec between start and error) I received PID and got environment variables using command `cat /proc/<PID>/environ`;
3. Environment variables set from the step 1 and step 2 were different. From the step 2 I didn't see all the variables with dash in the name

**Comment by dsame** [comment] 2022-07-11 07:53
@bissquit can you please attach the results of the inquires requested [here](https://github.com/actions/setup-java/issues/348#issuecomment-1171903926)

Unfortunately i can make only guesses about the problem having not enough info and i believe this is not docker problem - there's and issue with the pipeline itself passing no java-version input.

**Comment by bissquit** [comment] 2022-07-11 12:29
Yes, sure. I'll post it later

**Comment by bissquit** [comment] 2022-07-11 19:48
Here it is!

1. Full workflow scenario:
```
name: "Test Java action"

on:
  workflow_dispatch:

jobs:
  test-java:
    runs-on: [self-hosted, home]
    container:
      image: ubuntu:20.04

    steps:
      - name: Debug
        run: |
          set -x
          printenv
               
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          java-package: jdk+fx
          cache: gradle
```
2. Action in the build log (using self-hosted runner):
![image](https://user-images.githubusercontent.com/25527604/178343688-fdd6354e-b6e9-41da-b8b2-95f69a2a76d8.png)
3. With `ubuntu-latest` (or using github-hosted runners) downloading and unarchiving are Ok:
![image](https://user-images.githubusercontent.com/25527604/178343556-9224f4d6-4b64-4cca-95fc-a2be7fa87d21.png)


Before error I see the following environment variables of action's PID:
<details>
  <summary>Env of action's PID. Click to expand!</summary>
  
```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=<hostname>
HOME=/github/home
GITHUB_ACTIONS=true
CI=true
INPUT_DISTRIBUTION=zulu
INPUT_CACHE=gradle
INPUT_ARCHITECTURE=x64
INPUT_JDKFILE=
GITHUB_JOB=test-java
GITHUB_REF=refs/heads/test-branch
GITHUB_SHA=313186985ec554c3fbe2cc07e526f6917eda9d21
GITHUB_REPOSITORY=<owner>/<repo-name>
GITHUB_REPOSITORY_OWNER=<owner>
GITHUB_RUN_ID=2651821041
GITHUB_RUN_NUMBER=1
GITHUB_RETENTION_DAYS=90
GITHUB_RUN_ATTEMPT=6
GITHUB_ACTOR=<owner>
GITHUB_WORKFLOW=Test Java action
GITHUB_HEAD_REF=
GITHUB_BASE_REF=
GITHUB_EVENT_NAME=workflow_dispatch
GITHUB_SERVER_URL=https://github.com
GITHUB_API_URL=https://api.github.com
GITHUB_GRAPHQL_URL=https://api.github.com/graphql
GITHUB_REF_NAME=test-branch
GITHUB_REF_PROTECTED=false
GITHUB_REF_TYPE=branch
GITHUB_WORKSPACE=/__w/<repo-name>/<repo-name>
GITHUB_ACTION=__actions_setup-java
GITHUB_EVENT_PATH=/github/workflow/event.json
GITHUB_ACTION_REPOSITORY=actions/setup-java
GITHUB_ACTION_REF=v2
GITHUB_PATH=/__w/_temp/_runner_file_commands/add_path_4c32a692-e509-478a-9290-36582fb04964
GITHUB_ENV=/__w/_temp/_runner_file_commands/set_env_4c32a692-e509-478a-9290-36582fb04964
GITHUB_STEP_SUMMARY=/__w/_temp/_runner_file_commands/step_summary_4c32a692-e509-478a-9290-36582fb04964
RUNNER_DEBUG=1
RUNNER_OS=Linux
RUNNER_ARCH=X64
RUNNER_NAME=<runner-name>
RUNNER_TOOL_CACHE=/__w/_tool
RUNNER_TEMP=/__w/_temp
RUNNER_WORKSPACE=/__w/<repo-name>
ACTIONS_RUNTIME_URL=<runtime-url>
ACTIONS_RUNTIME_TOKEN=<token>
ACTIONS_CACHE_URL=<cache-url>
```
</details>

At the same time worker log is:

<details>
  <summary>Worker log. Click to expand!</summary>
  
```
[2022-07-11 19:15:16Z INFO ActionManifestManager] Loaded action.yml file: {
  "name": "Setup Java JDK",
  "description": "Set up a specific version of the Java JDK and add the command-line tools to the PATH",
  "inputs": {
    "type": 2,
    "map": [
      {
        "key": {
          "type": 0,
          "file": 3,
          "line": 6,
          "col": 3,
          "lit": "java-version"
        },
        "value": ""
      },
      {
        "key": {
          "type": 0,
          "file": 3,
          "line": 9,
          "col": 3,
          "lit": "distribution"
        },
        "value": ""
      },
      {
        "key": {
          "type": 0,
          "file": 3,
          "line": 12,
          "col": 3,
          "lit": "java-package"
        },
        "value": {
          "type": 0,
          "file": 3,
          "line": 15,
          "col": 14,
          "lit": "jdk"
        }
      },
      {
        "key": {
          "type": 0,
          "file": 3,
          "line": 16,
          "col": 3,
          "lit": "architecture"
        },
        "value": {
          "type": 0,
          "file": 3,
          "line": 19,
          "col": 14,
          "lit": "x64"
        }
      },
      {
        "key": {
          "type": 0,
          "file": 3,
          "line": 20,
          "col": 3,
          "lit": "jdkFile"
        },
        "value": ""
      },
      {
        "key": {
          "type": 0,
          "file": 3,
          "line": 23,
          "col": 3,
          "lit": "check-latest"
        },
        "value": {
          "type": 0,
          "file": 3,
          "line": 26,
          "col": 14,
          "lit": "false"
        }
      },
      {
        "key": {
          "type": 0,
          "file": 3,
          "line": 27,
          "col": 3,
          "lit": "server-id"
        },
        "value": {
          "type": 0,
          "file": 3,
          "line": 31,
          "col": 14,
          "lit": "github"
        }
      },
      {
        "key": {
          "type": 0,
          "file": 3,
          "line": 32,
          "col": 3,
          "lit": "server-username"
        },
        "value": {
          "type": 0,
          "file": 3,
          "line": 36,
          "col": 14,
          "lit": "GITHUB_ACTOR"
        }
      },
      {
        "key": {
          "type": 0,
          "file": 3,
          "line": 37,
          "col": 3,
          "lit": "server-password"
        },
        "value": {
          "type": 0,
          "file": 3,
          "line": 41,
          "col": 14,
          "lit": "GITHUB_TOKEN"
        }
      },
      {
        "key": {
          "type": 0,
          "file": 3,
          "line": 42,
          "col": 3,
          "lit": "settings-path"
        },
        "value": ""
      },
      {
        "key": {
          "type": 0,
          "file": 3,
          "line": 45,
          "col": 3,
          "lit": "overwrite-settings"
        },
        "value": {
          "type": 0,
          "file": 3,
          "line": 48,
          "col": 14,
          "lit": "true"
        }
      },
      {
        "key": {
          "type": 0,
          "file": 3,
          "line": 49,
          "col": 3,
          "lit": "gpg-private-key"
        },
        "value": ""
      },
      {
        "key": {
          "type": 0,
          "file": 3,
          "line": 52,
          "col": 3,
          "lit": "gpg-passphrase"
        },
        "value": ""
      },
      {
        "key": {
          "type": 0,
          "file": 3,
          "line": 56,
          "col": 3,
          "lit": "cache"
        },
        "value": ""
      },
      {
        "key": {
          "type": 0,
          "file": 3,
          "line": 59,
          "col": 3,
          "lit": "job-status"
        },
        "value": {
          "type": 3,
          "file": 3,
          "line": 61,
          "col": 14,
          "expr": "job.status"
        }
      }
    ]
  },
  "execution": {
    "executionType": "nodeJS",
    "hasPre": false,
    "hasPost": true,
    "script": "dist/setup/index.js",
    "pre": null,
    "post": "dist/cleanup/index.js",
    "nodeVersion": "node12",
    "cleanupCondition": "always()",
    "initCondition": "always()"
  },
  "deprecated": null
}
[2022-07-11 19:15:16Z INFO ActionManager] Action pre node.js file: N/A.

...
[2022-07-11 19:15:16Z INFO ProcessInvokerWrapper]   File name: '/snap/bin/docker'
[2022-07-11 19:15:16Z INFO ProcessInvokerWrapper]   Arguments: 'exec -i --workdir /__w/<repo-name>/<repo-name> -e INPUT_JAVA-VERSION -e INPUT_DISTRIBUTION -e INPUT_JAVA-PACKAGE -e INPUT_CACHE -e INPUT_ARCHITECTURE -e INPUT_JDKFILE -e INPUT_CHECK-LATEST -e INPUT_SERVER-ID -e INPUT_SERVER-USERNAME -e INPUT_SERVER*** INPUT_SETTINGS-PATH -e INPUT_OVERWRITE-SETTINGS -e INPUT_GPG-PRIVATE-KEY -e INPUT_GPG-PASSPHRASE -e INPUT_JOB-STATUS -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_DEBUG -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL 20f3553f1dcb0aaddc33e81ad81dfb846d9f5c363437c259577d48cc21769e77 /__e/node12/bin/node /__w/_actions/actions/setup-java/v2/dist/setup/index.js'
[2022-07-11 19:15:16Z INFO ProcessInvokerWrapper]   Working directory: '/home/github-runner/_work'
```
</details>

Where is the `INPUT_JAVA-VERSION` and other variables with `-` in the name in PID's env variables? Is it expected behavior?

**Comment by dsame** [comment] 2022-07-12 06:38
@bissquit thanks a lot for your input, i repeated the attempt to reproduce the problem and once again my build succeeded.

While i am investigating your worker log, can you please describe your host environment: os, os version and docker version?

**Comment by bissquit** [comment] 2022-07-12 18:03
Here is a command (formatted):
```
[2022-07-11 19:15:14Z INFO ProcessInvokerWrapper]   Arguments: 'create 
--name a3e2e37f95c04ed9873f44b518cc385c_ubuntu2004_d36244 
--label bc1331 --workdir /__w/<repo-name>/<repo-name>
--network github_network_92ee384d6b20418e9021c367bad0d05a  
-e "HOME=/github/home"
-e GITHUB_ACTIONS=true 
-e CI=true 
-v "/var/run/docker.sock":"/var/run/docker.sock" 
-v "/home/github-runner/_work":"/__w" 
-v "/home/github-runner/externals":"/__e":ro 
-v "/home/github-runner/_work/_temp":"/__w/_temp" 
-v "/home/github-runner/_work/_actions":"/__w/_actions" 
-v "/home/github-runner/_work/_tool":"/__w/_tool" 
-v "/home/github-runner/_work/_temp/_github_home":"/github/home" 
-v "/home/github-runner/_work/_temp/_github_workflow":"/github/workflow" 
--entrypoint "tail" ubuntu:20.04 "-f" "/dev/null"'
```
Do you mean action couldn't access repo files? Is it this action related problem or you think any action won't be able access repo files? Anyway I'll check it as soon as possible

**Comment by bissquit** [comment] 2022-07-14 19:06
Software info as you requested:
```
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
Linux github-runner-05 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ docker --version
Docker version 20.10.14, build a224086349
```

**Comment by bissquit** [comment] 2022-07-14 19:33
I got `docker create ...` command from the log file and then ran:
```
# docker create --name test_container \
              --workdir /__w/<repo-name>/<repo-name> \
              -e "HOME=/github/home" \
              -e GITHUB_ACTIONS=true \
              -e CI=true \
              -v "/var/run/docker.sock":"/var/run/docker.sock" \
              -v "/home/github-runner/_work":"/__w" \
              -v "/home/github-runner/externals":"/__e":ro \
              -v "/home/github-runner/_work/_temp":"/__w/_temp" \
              -v "/home/github-runner/_work/_actions":"/__w/_actions" \
              -v "/home/github-runner/_work/_tool":"/__w/_tool" \
              -v "/home/github-runner/_work/_temp/_github_home":"/github/home" \
              -v "/home/github-runner/_work/_temp/_github_workflow":"/github/workflow" \
              --entrypoint "tail" \
              ubuntu:20.04 \
              "-f" "/dev/null"

# docker start test_container

# docker exec -it \
            --workdir /__w/<repo-name>/<repo-name> \
            test_container \
            /bin/bash

root@5dc938451949:/__w/<repo-name>/<repo-name># ls -lha
total 20K
drwxr-xr-x 3 root root 4.0K Jul 14 19:08 .
drwxr-xr-x 3 root root 4.0K Jul 11 19:06 ..
drwxrwxr-x 3 root root 4.0K Jul 14 19:08 .github
-rw-rw-r-- 1 root root   35 Jul 14 19:08 build.gradle
-rw-rw-r-- 1 root root   12 Jul 14 19:08 file

root@5dc938451949:/__w/<repo-name>/<repo-name># ls -lha .github/workflows/test-java-action.yml
-rw-rw-r-- 1 root root 473 Jul 14 19:08 .github/workflows/test-java-action.yml

root@5dc938451949:/__w/<repo-name>/<repo-name># cat .github/workflows/test-java-action.yml
name: "Test Java action"

on:
  workflow_dispatch:

jobs:
  test-java:
#    runs-on: ubuntu-latest
    runs-on: [self-hosted, home]
    container:
      image: ubuntu:20.04

    steps:
      - name: Debug
        run: |
          set -x
          printenv

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          java-package: jdk+fx
          cache: gradle
```
- `<repo-name>` - replaced repo name;
- all env variables removed from docker commands except in `create` step

it looks like it works

**Comment by dsame** [comment] 2022-07-15 07:11
@bissquit Hello Egor, status update:

I am still not able to reproduce the problem and have to going to investigate the code in order to reach the point where the input can be lost. Meanwhile please try to replace `actions/setup-java@v2` with `actions/setup-java@v3` - little hope it helps but it is the only difference in the environments i see.

**Comment by dsame** [comment] 2022-07-16 21:45
Hello @bissquit,
just a status update.  The things very strange indeed.

I created a container named "nnn" and tried to emulate handling the variables with dashes as close to the runner's way

```
const { exec } = require("child_process");

process.env['VARXX_1A']='val_1'
process.env['VARXX-2A']='val-1'

// const ts='console.log(process.env["VARXX-2A"])'
const ts='console.log(process.env)'
const cl=`/__e/node12/bin/node -e '${ts}'`

exec(`docker exec -e VARXX_1A -e VARXX-2A -i  nnn ${cl}`, (error, stdout, stderr) => {
    if (error) {
        console.log(`error: ${error.message}`);
        return;
    }
    if (stderr) {
        console.log(`stderr: ${stderr}`);
        return;
    }
    console.log(`stdout: ${stdout}`);
});
```

As expected it prints only VARXX_1A value. So, strictly speaking, you observes the correct failure. But now there's a question  - how does it works for me? 

Can you please take a look at my pipeline? May be you can notice a difference with yours.
https://github.com/akv-demo/setup-java-test/runs/7372092315?check_suite_focus=true
workflow file: https://github.com/akv-demo/setup-java-test/blob/main/.github/workflows/blank.yml

JFI: my hosted agent is VM Ware machine with Ubuntu 22.04 and i also tried both docker.io from the Ubuntu distro and docker-ce 20.10.14 and 20.10.17 installed from docker site. All of them succeed in any circumstances.

**Comment by dsame** [comment] 2022-07-17 12:41
Hello @bissquit,

Can you please make sure the docker executable used be the runner is the binary file and not some shell wrapper around it? 

the snipet:
```
const child2 = spawn('/usr/bin/docker', ['exec','-e','VARXX_1A', 'VARXX-2A', '-i', 'nnn', cl])
child2.stdout.on('data', (data) => {
  console.log(`child stdout:\n${data}`);
});
```

shows the variables with dashes in their names are kept in the child process unless the process created without an intermediate shell level.

**Comment by dsame** [comment] 2022-07-20 06:29
hi @bissquit,

Oh, yeah! I believe if you do `file /usr/bin/docker` it shows something like `Bourne-Again shell script text executable, ASCII text` and that would be a case.

I recommend you to install docker with `apt-get install docker.io` - it is not critically outdated. The most recent docker can be installed as docker-ce (Docker Engine) for ubuntu from their site

**Comment by bissquit** [comment] 2022-07-21 18:44
Thank you, @dsame !
How do you think does it make sense to note in Action's docs that Docker installed by snap is not supported?

```
$ which docker
/snap/bin/docker
$ file /snap/bin/docker
/snap/bin/docker: symbolic link to /usr/bin/snap
$ file /usr/bin/snap
/usr/bin/snap: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=E1bSSt3SHLS0p7m5ZUWQ/XDfxM9_41BTy-aSSa2K3/-DKar1iqmwbcviwY13k-/wEfzirBnhFf52oC6mg7P, stripped
```

**Comment by dsame** [comment] 2022-07-25 07:16
@bissquit well, i think it make sense. I'll create i a ticket for github team to update the documentation and add a comment about their decision here.

**Comment by dsame** [comment] 2022-07-26 11:56
Documentation contribution is here https://github.com/github/docs/compare/main...dsame:docs:patch-1

@bissquit i'll move the issue to the Waiting for rollout state because there's nothing to do with it anymore and i will close it as soon as the documentation change will have been either approved or denied. But please feel free to create new issue or reopen this one in case if the problem not solved.
Thanks for the cooperation.

**Comment by dsame** [comment] 2022-10-06 09:26
@bissquit documentation is finally updated 
https://docs.github.com/en/actions/hosting-your-own-runners/monitoring-and-troubleshooting-self-hosted-runners#checking-which-docker-engine-is-installed-on-the-runner

I am closing the issue as resolved but please feel free to reopen it or create new one in case you think the problem still exists

**Closed by dsame** 2022-10-06 09:26 UTC
Labels: bug

**Comment by bissquit** [comment] 2022-10-06 18:16
Looks great! Thank you so much!
