### ISSUE TITLE
502 Bad Gateway when trying to run actions/setup-java@v3

### ISSUE THREAD

**Issue by mihaelmulesoft** [actions/setup-java#462] opened 2023-03-09 12:54 UTC
**Description:**
The action suddenly stopped working 15min ago. All workflows containing the setup-java@v3 step are breaking with the message: 502 Bad Gateway

**Task version:**
actions/setup-java@v3

**Platform:**
 Ubuntu

**Runner type:**
Self-hosted

**Repro steps:**  
Run any workflow containing actions/setup-java@v3

**Expected behavior:**
Java jdk should be installed on the vm

**Actual behavior:**
workflow fails.
![Bildschirm­foto 2023-03-09 um 13 49 37](https://user-images.githubusercontent.com/29606687/224029187-ec871944-f953-48e2-b713-4a194b195c1f.png)

**Comment by BartlomiejAdamiak-TomTom** [comment] 2023-03-09 12:58
We have seen same thing in our workflows

**Comment by rtc11** [comment] 2023-03-09 13:04
Adoptium has problems, works if you change distribution to something else

**Comment by BartlomiejAdamiak-TomTom** [comment] 2023-03-09 13:04
Temurin distribution does not work as well

**Comment by xshara** [comment] 2023-03-09 13:13
Seems to be working again now

**Comment by mihaelmulesoft** [comment] 2023-03-09 13:34
seems to be working again.

**Comment by IvanZosimov** [comment] 2023-03-09 15:33
Hi, all 👋 Sorry for the inconvenience, seems like it was a temporary problem with the Adoptium API. Now I can confirm that everything works as expected: https://github.com/actions/setup-java/actions/runs/4375687483
I'm closing this issue now, thank you for the fast signaling! ❤️

**Closed by IvanZosimov** 2023-03-09 15:33 UTC
Labels: bug

**Comment by mheing-epro** [comment] 2023-03-09 16:13
@IvanZosimov may I ask you to elaborate something w. r. t. this issue today? We use `temurin` JRE for v`17`, which according to the [docs](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#hosted-tool-cache) appears to be cached locally/on GitHub somewhere. Also, we do _not_ have `check-latest` enabled.

How come that this Adoptium API problem was bothering us then? We were assuming that there is no need to poll any 3rd party when using these settings.

**Comment by IvanZosimov** [comment] 2023-03-10 08:42
Thanks, @mheing-epro! We will take a look!

**Comment by johnoliver** [comment] 2023-03-10 12:25
@IvanZosimov I believe the issue is in:

https://github.com/actions/setup-java/blob/main/src/distributions/base-installer.ts#L50 

If I understand this code correctly, either checkLatest is false, in which case it will use the local cached version without the external api hit, but you might use an out of date version. Or checkLatest is true in which case a successful hit to the external api MUST succeed even if you have a cached version available. My guess is you really want 3 behaviours:

1. Use local cache without checking the api
2. Only proceed if you have checked with upstream API and confirmed you are using the latest version
3. Check with the upstream API if possible, if it fails just use whats in the cache

**Comment by mheing-epro** [comment] 2023-03-10 17:35
We use runners hosted by GitHub, it's plain simple

```yaml
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          java-package: jre
```

**Comment by IvanZosimov** [comment] 2023-03-13 10:05
Thanks for the information, @mheing-epro! As I see you're using `java-package` input and set it to `jre`. The thing is that on the runners we have precached `jdk` Temurin. That's why, when the API was down, action didn't work as expected for you. If it's OK for you to setup JDK instead of JRE, you can change `jre` -> `jdk` and action will use precached JDK in case of any external problems.

**Comment by mheing-epro** [comment] 2023-03-13 11:28
Alright, the limitation to the JDK here wasn't explicit in the docs, but we can use as a workaround then. Thanks.
