### ISSUE TITLE
Setup java takes much too long

### ISSUE THREAD

**Issue by joshiste** [actions/setup-java#130] opened 2021-03-03 11:05 UTC
**Description:**
Currently I'm experiencing extreme slow build times because setup-java takes more than 10 minutes

**Task version:**
v1

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  
```
jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
```

**Expected behavior:**
In the past the step only took a couple of seconds.

**Actual behavior:**
The step takes more than 10 minutes. May be missing caching and slow download servers?
Restarting doesn't help.

**Comment by maxim-lobanov** [comment] 2021-03-03 11:39
Hello @joshiste, currently, we are working on implementation actions/setup-java@v2.
One of the major feature will be consuming Java versions pre-installed on images that should significantly reduce task time. We are expecting V2 to be available in a couple of weeks.

**Comment by iamKunalGupta** [comment] 2021-03-03 11:40
> Hello @joshiste, currently, we are working on implementation actions/setup-java@v2.
> One of the major feature will be consuming Java versions pre-installed on images that should significantly reduce task time. We are expecting V2 to be available in a couple of weeks.

Hi @maxim-lobanov This issue was not there yesterday for the same exact setup for me (v1) and has just started occurring out of the blue right now.

**Comment by maxim-lobanov** [comment] 2021-03-03 11:45
Yes, I think it could be caused by some temporary connection issues / slowness on Azul CDN. actions/setup-java@v1 downloads Java directly from Azul site: https://www.azul.com/downloads/zulu-community/?package=jdk

**Comment by swanandvk** [comment] 2021-03-03 11:52
Experiencing the same , its taking around 19 mins to complete

**Comment by mdreizin** [comment] 2021-03-03 11:53
The same for me.

**Comment by joshiste** [comment] 2021-03-03 12:52
seems to be good again.

**Comment by dmitry-shibanov** [comment] 2021-03-16 16:15
Hello everyone. I am closing the issue because it was a temporary Azul's server side issue. If you have any concerns, feel free to reopen the issue.

**Closed by dmitry-shibanov** 2021-03-16 16:15 UTC
Labels: bug
