### ISSUE TITLE
Provide JDK 18

### ISSUE THREAD

**Issue by apupier** [actions/setup-java#304] opened 2022-03-25 13:36 UTC
**Description:**

For Oracle OpenJDK 18 has been released. https://openjdk.java.net/projects/jdk/18/

For AdoptOpenJDK, I think it is related to the Temurin and so to this ticket https://github.com/adoptium/adoptium/issues/130

For Zulu, seems it is released https://docs.azul.com/core/zulu-openjdk/release-notes/18-ga

For Liberica, seems available https://bell-sw.com/pages/downloads/#/java-18-current

For Microsoft, build not available currently on https://docs.microsoft.com/en-us/java/openjdk/download but might never be available as itis nto a LTS. based on https://docs.microsoft.com/en-us/java/openjdk/faq 
>We plan to release OpenJDK binaries for versions where there is mutual LTS consensus across OpenJDK contributors and vendors.

**Justification:**

JDK 18 is the latest release of Java.

**Are you willing to submit a PR?**
maybe for AdoptOpenJDK/Temurin when available if it is a low effort

**Comment by dmitry-shibanov** [comment] 2022-03-28 09:35
Hello @apupier. Thank you for your proposal. The action uses API to grab the latest versions of distributions. I can confirm that the Java 18 for Ubuntu can be installed for Liberica, Zulu and Temurin. Unfortunately, for Microsoft the action does not have an API to grab all available versions.

**Comment by JohannesLichtenberger** [comment] 2022-03-31 22:43
Would be awesome, my builds currently fail, as I switched a project already to Java 18.

**Comment by dmitry-shibanov** [comment] 2022-03-31 23:09
Hello @JohannesLichtenberger. What distribution and os are you using?

**Comment by JohannesLichtenberger** [comment] 2022-03-31 23:30
Ubuntu / Temurin, but actually I don't care which distribution :)

The workflow is this:
https://github.com/sirixdb/sirix/blob/master/.github/workflows/gradle.yml

**Comment by dmitry-shibanov** [comment] 2022-03-31 23:42
I think it's not an issue with setup-java itself, because the version setup step worked correctly.

**Comment by RealYusufIsmail** [comment] 2022-04-12 18:01
I am having an issue were it is recognising java adopt 18.

**Comment by jachro** [comment] 2022-04-12 18:42
> I am having an issue were it is recognising java adopt 18.
> 
> `Could not find satisfied version for SemVer '18'. `
> 
> This is what I have
> 
> ```yaml
>  - name: Set up JDK 18
>         uses: actions/setup-java@v3.1.1
>         with:
>           java-version: '18'
>           distribution: 'adopt'
> ```

I had the same problem and switching over to `temurin` did the trick:
```yaml
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
```

**Comment by RealYusufIsmail** [comment] 2022-04-12 19:05
> > I am having an issue were it is recognising java adopt 18.
> > `Could not find satisfied version for SemVer '18'. `
> > This is what I have
> > ```yaml
> >  - name: Set up JDK 18
> >         uses: actions/setup-java@v3.1.1
> >         with:
> >           java-version: '18'
> >           distribution: 'adopt'
> > ```
> 
> I had the same problem and switching over to `temurin` did the trick:
> 
> ```yaml
>         uses: actions/setup-java@v3
>         with:
>           distribution: 'temurin'
>           java-version: '18'
> ```

Thank you very much.

**Comment by dmitry-shibanov** [comment] 2022-04-18 14:28
Hello everyone. Java 18 is available for AdoptOpenJDK (Temurin), Zulu and Liberica. The setup-java action does not provide Oracle. We have a separate issue with add it https://github.com/actions/setup-java/issues/69. For Microsoft builds are not available for now. 

For now I'm going to close the issue.  If you have any concerns feel free to ping us.

**Closed by dmitry-shibanov** 2022-04-18 14:28 UTC
Labels: feature request
