### ISSUE TITLE
Fallbacks when jdk cannot be downloaded

### ISSUE THREAD

**Issue by ben-manes** [actions/setup-java#333] opened 2022-05-26 17:28 UTC
**Description:**
Sometimes the JDK cannot be retrieved. In this [execution](https://github.com/ben-manes/caffeine/runs/6613492750?check_suite_focus=true#step:5:25), Cloudflare responded with a `Please Wait...` html payload which the action did not understand.

It would be nice if (a) a retry approach was implemented, (b) if fallback distributions could be set. If the execution allows for any compatible OpenJDK distribution, then this failure could be mitigated.

**Justification:**
Execution failures due to external systems, where a retry and fallback policy could allow the action to recover and not cause noise.

**Comment by e-korolevskii** [comment] 2022-05-27 08:07
Hello @ben-manes,
Thank you very much for your request!
We are considering your feature request and will inform you about it.
Thank you for your patience.

**Comment by ben-manes** [comment] 2022-05-30 17:20
I switched to `temurin` to take advantage of the `tool-cache` for jdk11 and for jdk18 that it is hosted on github packages (so maybe fewer cdn quirks). That was close but not enough, so I wrapped it using `wretry.action` like below. Unfortunately that skips the built-in caching due to being "loaded as a module", so that has to be done separately (e.g. via `gradle-build-action`). This might be good enough, if you prefer to document that as a workaround.

```yaml
- name: Set up JDK ${{ matrix.java }}
  uses: Wandalen/wretry.action@v1.0.20
  with:
    action: actions/setup-java@v3
    with: |
      distribution: temurin
      java-version: ${{ matrix.java }}
    attempt_limit: 3
    attempt_delay: 2000
```

**Comment by e-korolevskii** [comment] 2022-06-01 15:15
Hello @ben-manes,

Thanks for suggesting this workaround. After investigation, we decided that the problem was in the occurrence of captcha (you can learn more about this in issue #[334](https://github.com/actions/setup-java/issues/334)) and as _giltene_ [answered](https://github.com/actions/setup-java/issues/334#issuecomment-1141451785) - they solved this problem on their side. 
We will keep an eye at the situation and investigate the possibility of implementing this feature.

**Comment by e-korolevskii** [comment] 2022-06-01 17:37
Good evening, @ben-manes 
We will try to reproduce this error with the network and explore the possibilities of solving this problem.

**Comment by e-korolevskii** [comment] 2022-06-03 13:29
Hey @ben-manes,

After investigation we came to the conclusion that the problem was caused by the _Harden Runner_. Because one of the polled addresses was not on the allowed list. A simple solution in this situation, we see adding the address `54.185.253.63:443` to the list of allowed endpoints.
Does this solve your problem?

**Comment by ben-manes** [comment] 2022-06-03 15:44
great, thanks @e-korolevskii!

**Comment by e-korolevskii** [comment] 2022-06-06 08:04
Hello @ben-manes,

Thanks for the note, it might be very helpful for other users. For now, I'll close this issue as resolved. If you have additional questions - feel free to ask them here or create a separate issue.

Have a good day!

**Closed by e-korolevskii** 2022-06-06 08:04 UTC
Labels: feature request
