### ISSUE TITLE
Cache gets slower over time

### ISSUE THREAD

**Issue by Dogacel** [actions/setup-java#487] opened 2023-04-25 16:36 UTC
**Description:**

The cached build gets slower over time.

**Task version:**
v3.11.0

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Repro steps:**  

1. Create a scala, sbt project with build workflow.
2. Cache `target/` directory between runs to run `sbt compile` incrementally in consequtive commits in a PR.
3. Wait a couple days and re-try.

**Expected behavior:**

Because we don't have any snapshot dependencies, cache sped should be preserved. 

**Actual behavior:**
Whenever our `sbt` cache gets older, probability of it running slower increases. 

I have realized no console log is given during this time, meaning no actual compilation happens but something

This is the average runtime for our workflow runs over time.

![image](https://user-images.githubusercontent.com/7023385/234343471-a7819b2a-4498-4b67-ade3-53a9b8e210d9.png)

Sometimes the average goes down because sbt cache is refreshed. The average goes down slower as the existing PRs that use the old cache is closed. 

I suspect might be related to #408 as sbt relies on both JDK / JRE hashes and dependency hashes. 

In our case, the incremental build goes from `2m` to `8m` slowly. And it never exceeds 8 minutes. I also measured `sbt update` time which is around 6 minutes. I suspect update is happening even though the cache is there.

**Comment by dmitry-shibanov** [comment] 2023-04-25 23:22
Hello @Dogacel. Thank you for your report. We'll take a look on this issue.

**Comment by dsame** [comment] 2023-11-27 13:46
Hello @Dogacel , i am closing the issue because of it is not reproducible. Feel free to create a new one or reopen this in case the problem still exists.

**Closed by dsame** 2023-11-27 13:46 UTC
Labels: bug
