### ISSUE TITLE
When Trying to run mvn package --file pom.xml getting error from repo.maven.org

### ISSUE THREAD

**Issue by vishalvrv9** [actions/setup-java#485] opened 2023-04-20 01:51 UTC
**Description:**
The actions/setup-java@v3 was working until today afternoon. Same workflow.yml. But since 5pm EDT today, it is giving an error saying

```
Error:      Non-resolvable import POM: Could not transfer artifact org.springframework.session:spring-session-bom:pom:2021.2.0 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/springframework/session/spring-session-bom/2021.2.0/spring-session-bom-2021.2.0.pom @ org.springframework.boot:spring-boot-dependencies:2.7.9-SNAPSHOT, /home/runner/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.7.9-SNAPSHOT/spring-boot-dependencies-2.7.9-SNAPSHOT.pom, line 2781, column 19: Unknown host repo.maven.apache.org -> [Help 2]
```
I am able to run the mvn same command on my local machine without any errors. The maven version on my local and the workflow also appears to be the same. 

**Task version:**
actions/setup-java@v3
JDK 19
Maven 3.8.8

**Platform:**
Ubuntu
**Runner type:**
Hosted

**Repro steps:**  
Running the below action yields error.
```
name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
```

**Expected behavior:**
mvn build should succeed

**Actual behavior:**
gives the error mentioned above

EDIT: Formatting

**Comment by ctevse** [comment] 2023-04-20 02:02
+1 I started receiving errors in my Workflows when running `mvn package`

```
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-dependency-plugin/2.8/maven-dependency-plugin-2.8.pom
Warning:  Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-dependency-plugin:2.8: Plugin org.apache.maven.plugins:maven-dependency-plugin:2.8 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-dependency-plugin:jar:2.8

Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
Warning:  Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-clean-plugin:2.5: Plugin org.apache.maven.plugins:maven-clean-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:2.5

Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom
Warning:  Failed to retrieve plugin descriptor for org.apache.maven.plugins:maven-resources-plugin:2.6: Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.6

...

Error:  No plugin found for prefix 'install' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/runner/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
```

Current runner version: '2.303.0'
Operating System
  Ubuntu
  20.04.6
  LTS
Runner Image
  Image: ubuntu-20.04
  Version: 20230409.1
  Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20230409.1/images/linux/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230409.1
Runner Image Provisioner
  2.0.139.1
Download action repository 'actions/setup-java@v3' (SHA:5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2)

**Comment by vishalvrv9** [comment] 2023-04-20 02:03
https://github.com/rajatkrishna/demo

A friend tried it as a different user and getting the same error

**Comment by wu-json** [comment] 2023-04-20 02:05
+1 here this is causing all of our builds to fail.

**Comment by ctevse** [comment] 2023-04-20 02:09
Reviewing some of the logs further, I found that the difference between our passing build and failing build was in the runner version. 
It seems this may be an issue with the runner-images, not setup-java. Someone created an issue there https://github.com/actions/runner-images/issues/7465

**Comment by wu-json** [comment] 2023-04-20 02:17
@ctevse I think you're right. I just retried our builds using `actions/setup-java@v2` and am getting the same issues unfortunately.

**Comment by IvanZosimov** [comment] 2023-04-20 06:54
Hi, all 👋 Thanks for the issue, we are working on it!

**Comment by IvanZosimov** [comment] 2023-07-07 13:36
I'm closing this issue, as it was a temporary problem caused by the https://repo.maven.apache.org/

**Closed by IvanZosimov** 2023-07-07 13:36 UTC
Labels: external
