### ISSUE TITLE
Derive architecture from underlying runner machine architecture

### ISSUE THREAD

**Issue by bbednarek** [actions/setup-java#418] opened 2022-12-03 10:25 UTC
**Description:**
The target architecture parameter has default value: `x64`. It would be nice to derive it from underlying runner machine architecture e.g. if the runners run on `ARM64` then default value would be `aarch64`.

**Justification:**
The aim is to keep the github runner pipelines agnostic to the underlying architecture of the machine where it runs e.g. we are migrating from `X64` to `ARM64` machines and it would be great to keep generic pipeline with a following step
```
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'
```
instead of specifying `architecture` parameter. Such a change would be backward compatible, because the default value `x64` would stay if underlying machine is `X64`.

Alternative solution would be to accept `RUNNER_ARCH` [environment variable](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables) as default, but even now supplying it without additional mapping is not possible, because  possible values (`X86`, `X64`, `ARM`, or `ARM64`) are not compatible with `architecture` parameter. 

**Are you willing to submit a PR?**
I am not familiar with Typescript, but I can try :)

**Comment by dmitry-shibanov** [comment] 2022-12-04 22:24
Hello @bbednarek. Thank you for your feature request. Actually, we had a similar [pull request](https://github.com/actions/setup-java/pull/376) to resolve the issue. Does the issue reproduce on the self-hosted agent ?

Could you please send the SHA for setup-java ? You can find it in `Set up job` step:
<img width="746" alt="image" src="https://user-images.githubusercontent.com/28229110/205518875-2bac2817-fe40-485c-b3ac-edb8e149fd2e.png">

**Comment by bbednarek** [comment] 2022-12-05 19:57
@dmitry-shibanov thanks for the quick suggestion. I double check it and it turns out that I was using `actions/setup-java@v2`. Once I upgraded to `actions/setup-java@v3` everything works.
It would be nice to update [documentation](https://github.com/actions/setup-java#usage) though.

**Comment by dmitry-shibanov** [comment] 2022-12-05 22:35
Thank you for your response @bbednarek. I'll keep the issue opened until we make changes to the documentation.

**Comment by panticmilos** [comment] 2022-12-20 12:46
hi @bbednarek, I will close this issue since we adapted the documentation by your suggestion :)

**Closed by panticmilos** 2022-12-20 12:46 UTC
Labels: documentation
