### ISSUE TITLE
502 Bad Gateway with `v2`

### ISSUE THREAD

**Issue by sormuras** [actions/setup-java#161] opened 2021-04-12 06:52 UTC
Using:

```yaml
      - name: 'Set up JDK'
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
```

Leads (sometimes) to:

![image](https://user-images.githubusercontent.com/2319838/114352389-1a99ea80-9b6c-11eb-8433-c698f8e0a915.png)

https://github.com/sormuras/bach-application-template/runs/2321248297?check_suite_focus=true

Note: Jobs running on macOs and Windows in parallel did manage to setup Java as expected.

**Comment by dmitry-shibanov** [comment] 2021-04-12 07:24
Hello @sormuras. Thank you for report. Could you please answer some more question.
 - How often does it reproduce ?
 - On which configurations the error is reproduced ?

**Comment by sormuras** [comment] 2021-04-12 07:29
> How often does it reproduce ?

Saw it only once. So zero times **re**produced, yet.

> On which configurations the error is reproduced ?

Hosted.

```text
Current runner version: '2.277.1'
Operating System
  Ubuntu
  20.04.2
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210405.1
...  
```

Find more details at https://github.com/sormuras/bach-application-template/runs/2321248297

**Comment by dmitry-shibanov** [comment] 2021-04-12 08:12
Thank you for providing information @sormuras. We added schedule for e2e in scope of this [pull request](https://github.com/actions/setup-java/pull/162) to monitor this issue.

**Comment by dmitry-shibanov** [comment] 2021-04-20 08:37
Hello @sormuras. We added schedule for e2e tests and didn't see any errors. Could you please confirm that you hadn't faced up with this issue since last time you reported ?

**Comment by sormuras** [comment] 2021-04-20 08:40
Aye, Dmitry. The error didn't occur again - so far.

**Comment by maxim-lobanov** [comment] 2021-04-21 08:17
As Dmitry mentioned, we have added e2e tests scheduled twice per day (every test runs about [~150 test cases](https://github.com/actions/setup-java/blob/main/.github/workflows/e2e-versions.yml)) and didn't reproduce this issue for the last week.
I will close this issue for now but we will keep these tests scheduled and will monitor them. Please let us know if you see this issue again.
If it reproduces, we definitely should consider adding some kind of retry logic for action.

**Closed by maxim-lobanov** 2021-04-21 08:17 UTC
Labels: bug

**Comment by joel-costigliola** [comment] 2021-06-16 10:49
this occured in https://github.com/assertj/doc/runs/2838393644?check_suite_focus=true

**Comment by joel-costigliola** [comment] 2021-06-16 10:55
and it's ok now.

**Comment by tshirtman** [comment] 2021-10-30 11:40
Hello,
This happened more than a few times today to me, forcing a trigger of all versions of the job again, each one having a non-null chance of failing…

https://github.com/kivy/pyjnius/runs/4054696309?check_suite_focus=true
https://github.com/kivy/pyjnius/runs/4054612694?check_suite_focus=true
https://github.com/kivy/pyjnius/runs/4054612794?check_suite_focus=true
https://github.com/kivy/pyjnius/runs/4054501552?check_suite_focus=true
https://github.com/kivy/pyjnius/runs/4054501596?check_suite_focus=true
https://github.com/kivy/pyjnius/runs/4054449871?check_suite_focus=true
