### ISSUE TITLE
> **Description:**

### ISSUE THREAD

**Issue by Chuysalgafo** [actions/setup-java#655] opened 2024-07-21 17:47 UTC
> **Description:**
> Dragonwell version parsing failed. Because Dragonwell adds a few more versions to its own version number based on the upstream OpenJDK, calling semver function directly will produce an incorrect version number.
> 
> **Task version:**
> Nightly task.
> 
> **Platform:**
> - [x] Ubuntu
> - [x] Windows
> 
> **Runner type:**
> - [x] Hosted
> - [x] Self-hosted
> 
> **Expected behavior:**
> get correct version number.
> 
> **Actual behavior:**
- [ ] > get wrong version number, such as17.0.1.0.1+12 will be parsed to 17.0.1+0.1+12.

_Publicado originalmente por @Chuysalgafo en https://github.com/actions/setup-java/issues/642#issuecomment-2241724781_

**Comment by Chuysalgafo** [comment] 2024-07-21 17:48
> > **Description:**
> > Dragonwell version parsing failed. Because Dragonwell adds a few more versions to its own version number based on the upstream OpenJDK, calling semver function directly will produce an incorrect version number.
> > 
> > **Task version:**
> > Nightly task.
> > 
> > **Platform:**
> > - [x] Ubuntu
> > - [x] Windows
> > 
> > **Runner type:**
> > - [x] Hosted
> > - [x] Self-hosted
> > 
> > **Expected behavior:**
> > get correct version number.
> > 
> > **Actual behavior:**
- [ ] > - [ ] > get wrong version number, such as17.0.1.0.1+12 will be parsed to 17.0.1+0.1+12.
> 
> 
> 
> _Publicado originalmente por @Chuysalgafo en https://github.com/actions/setup-java/issues/642#issuecomment-2241724781_

**Comment by mahabaleshwars** [comment] 2024-07-22 10:26
Hello @Chuysalgafo, I'm closing the issue as a duplicate of #642.

**Closed by mahabaleshwars** 2024-07-22 10:26 UTC
