### ISSUE TITLE
Document input variables

### ISSUE THREAD

**Issue by alwyn** [actions/setup-java#382] opened 2022-09-16 14:32 UTC
**Description:**
The current documentation focuses on things like caching and lists all the java distributions you can provide in the configurations.  It however doesn't cover any of the other values that can be provided using 'with:' like server-id etc.

**Justification:**
It just makes sense for users to have documentation on the options so that they don't need to read the source.

**Are you willing to submit a PR?**
No, due to over work-load.

**Comment by dsame** [comment] 2022-09-19 08:39
@alwyn thanks for you note, we will double check the documentation and most probably add the necessary info.

**Comment by dsame** [comment] 2022-09-27 10:25
@alwyn I am closing this issue because of https://github.com/actions/setup-java/pull/387

Please feel free to reopen the issue or create another one in case if the problem is not resolved.

**Closed by dsame** 2022-09-27 10:25 UTC
Labels: feature request
