### ISSUE TITLE
maven cache is not found

### ISSUE THREAD

**Issue by hajjoujti** [actions/setup-java#577] opened 2023-12-28 02:09 UTC
**Description:**
I am having an issue on my workflows because they are saving the cache at the Post Set Up Java but the cache is not found in the next time this workflow is being triggered.
I have three workflows and all three are behaving the same.

*Set Up Java:*
```
Run actions/setup-java@v4.0.0
Installed distributions
Creating settings.xml with server-id: ossrh
Writing to /home/runner/.m2/settings.xml
Importing private gpg key
maven cache is not found
```

*Post Set Up Java:*
```
Post job cleanup.
Removing private key from keychain
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/jumble-juggler/jumble-juggler --files-from manifest.txt --use-compress-program zstdmt
Cache Size: ~21 MB (22524066 B)
Cache saved successfully
Cache saved with the key: setup-java-Linux-maven-2ce1e5c635a93fe6e2777be9e471759542e7a1e7c394f7baf484fee1a0985f95
```

**Task version:**
Specify the task version

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Repro steps:** 
It is a public repository: https://github.com/jumble-juggler/jumble-juggler
The three YAML file are in .github/workflows

**Expected behavior:**
Should use the cache maven.

**Actual behavior:**
maven cache is not found and it is saving the cache every time which takes a lot of time.

**Comment by IvanZosimov** [comment] 2023-12-28 09:12
Hi, @hajjoujti 👋 Thanks for the bug report, we will take a look!

**Comment by helpermethod** [comment] 2024-01-03 14:30
Because of this problem, my build time has doubled 😢.

**Comment by antonmos** [comment] 2024-01-11 22:57
same problem when using `cache: 'gradle'` option

**Comment by bakoontz2** [comment] 2024-06-12 22:20
Same here, cache is being created in post-action step but not being found in next run...

**Comment by priya-kinthali** [comment] 2024-06-25 09:21
Hello @hajjoujti 👋,
Thank you for your report. I couldn't replicate the cache issue you mentioned and the caching mechanism working as intended.
To help resolve the issue, I suggest considering the following aspects:

* **Cache Invalidation**: It's worth noting that the caching mechanism in workflows often uses the hash of certain files like pom.xml as part of the cache key. If these files are modified, it changes the hash and hence the cache key, which could be causing the cache recognition discrepancies you're observing. To ensure consistent caching, make sure these files stay the same across workflow runs.
* **Parallel Workflow Runs**: In the instance of multiple workflows operating concurrently, there's a possibility of cache overlaps which can cause conflicts. A potential solution for this is to strategically schedule your workflows to prevent them from running simultaneously. This way, each workflow can efficiently utilize the cache without the risk of overwriting another's cache data.

Additionally, there have been similar reports about the `maven` cache not being used when workflows have different targets. Please see if this [issue](https://github.com/actions/setup-java/issues/255) is relevant to your situation.
If you're having issues with the `gradle` cache, please refer to this [issue](https://github.com/actions/setup-java/issues/514) and see if the discussion there is relevant to your case.
I hope this information is helpful.

**Comment by priya-kinthali** [comment] 2024-07-03 11:56
Hello @hajjoujti, Just checking in to see if you had a chance to review the suggestions provided earlier regarding the cache issue in your workflows. Please let us know if the information was helpful or if you need further assistance. Thank you!

**Comment by hajjoujti** [comment] 2024-07-03 12:00
Hello,
Sadly I didn't have the time to check it out and it's been a while I didn't work on this project. I'm not sure when I will have the time to check it out.
I think it is safe to close this issue and I will recomment here if when I check it out again.

**Comment by priya-kinthali** [comment] 2024-07-04 04:36
Hello @hajjoujti 👋,
Thank you for the update. I'll go ahead and close this issue for now. Please feel free to reopen it or comment here if you have any updates or encounter the problem again.
Thank you for your understanding and cooperation:)

**Closed by priya-kinthali** 2024-07-04 04:36 UTC
Labels: bug
