### ISSUE TITLE
Support for GraalVM

### ISSUE THREAD

**Issue by morki** [actions/setup-java#195] opened 2021-07-15 15:22 UTC
**Description:**
It would be nice to support GraalVM Community Edition JDK.

**Justification:**
It is already available in Github Actions virtual environments.

**Are you willing to submit a PR?**
Sorry but no, I don't have enought knowledge.

**Comment by maxim-lobanov** [comment] 2021-07-15 15:25
@morki , have you tried the community action for GraalVM?
https://github.com/marketplace/actions/setup-graalvm-environment

**Comment by morki** [comment] 2021-07-15 15:32
Yes, but with this action we can use matrix builds for many JDKs and soon it will hopefully be support for Gradle / Maven caching here.

**Comment by gotson** [comment] 2021-09-02 03:36
And we could have cache for gradle/maven also 👍🏻

**Comment by overheadhunter** [comment] 2022-02-03 06:11
Just for the record, here is a link to yet another [`graalvm/setup-graalvm` action](https://github.com/marketplace/actions/github-action-for-graalvm), provided by graalvm team.

**Comment by zharinov** [comment] 2022-02-03 14:09
Although official [setup-graalvm](https://github.com/graalvm/setup-graalvm/) action definitely would handle graal-specific extensions better, is someone interested in `graalvm` support for `setup-java` anyway? I think it doesn't make too much sense to support additional GraalVM components, but I'm about to open PR that implements basic GraalVM JDK install.

**Comment by sebthom** [comment] 2023-01-27 10:12
I am also very interested in seeing setup-java provide graalvm support, so it can be used in matrix builds to easily test it against other JDK providers. 

@zharinov is willing to provide a PR implementing this, but wants a signal from the maintainers (e.g. @dmitry-shibanov @IvanZosimov @marko-zivic-93) of this repo that there actually is interest in such a contribution. can one of you guys please confirm this? thanks a lot in advance!

**Comment by IvanZosimov** [comment] 2023-01-27 13:07
Hi, @sebthom 👋 Thanks for the comment! We are currently investigating the license of the GraalVM JDK. As soon as we finish this process we will get back to you with additional information.

**Comment by IvanZosimov** [comment] 2023-03-22 14:07
Hi, @all 👋 Unfortunately, during the investigation it was decided not to add support of GraalVM to setup-java action. The reason for this decision is existence of the official GraalVM action: https://github.com/marketplace/actions/github-action-for-graalvm
I'm going to close this issue, if you have any question feel free to ask them.

**Closed by IvanZosimov** 2023-03-22 14:07 UTC
Labels: feature request

**Comment by sebthom** [comment] 2023-03-22 14:16
@IvanZosimov That is more than disappointing. The problem is, that even if this action is available it does not solve the usecase of matrix builds with different JDK vendors when GraalVM should be included. 

This decision is also incomprehensible because someone from the community (@zharinov) even offers to implement it.

**Comment by SethTisue** [comment] 2023-03-22 22:42
> it does not solve the usecase of matrix builds with different JDK vendors when GraalVM should be included

this seems like a pretty powerful argument

**Comment by IvanZosimov** [comment] 2023-03-23 08:08
Hi, @sebthom and @SethTisue , thanks for the comments. You can use the above-mentioned action in a separate job, it will have the same effect as the additional member of matrix.

**Comment by Marcono1234** [comment] 2024-11-02 00:48
Looks like this has actually been implemented by #501 in the meantime
