### ISSUE TITLE
Error while using maven-gpg-plugin after setting GPG data

### ISSUE THREAD

**Issue by Lycoon** [actions/setup-java#554] opened 2023-11-15 23:00 UTC
**Description:**
I set my GPG private key and passphrase through setup-java action, the problem is, the maven-gpg-plugin seems to fail at retrieving them from settings.xml prompting the following message: `gpg: Sorry, no terminal at all requested - can't get input`.

**Task version:**
actions/setup-java@v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
I am currently trying to make it work on [this](https://github.com/Lycoon/clash-api) repo.
The GitHub Actions workflow file can be found [here](https://github.com/Lycoon/clash-api/blob/dev/.github/workflows/deploy.yml) and the pom.xml file at the root of the repository.

**Comment by IvanZosimov** [comment] 2023-11-16 08:45
Hi, @Lycoon 👋 Thanks for the issue, we will take a look and get back to you as soon as we have updates.

**Comment by IvanZosimov** [comment] 2023-11-16 11:05
@Lycoon, I've checked out and tested your solution. It seems that `setup-java` works correctly as `gpg key` is imported and `settings.xml` is created correctly. I suspect that the problem is inside your `pom.xml` file or in the `mvn deploy` command itself. I see that you use Profile named `sign` and the settings inside it seems OK to me, but does maven use it? Could you, please, enable debug logging for maven and share the logs with us?

**Comment by Lycoon** [comment] 2023-11-16 14:17
Sure, here are the logs with debug logging enabled: https://github.com/Lycoon/clash-api/actions/runs/6891906456/job/18748011968.

**Comment by IvanZosimov** [comment] 2023-11-17 11:31
@Lycoon, Thank you! Could you, please, try to update version of the `maven-gpg-plugin` to 1.6?

**Comment by Lycoon** [comment] 2023-11-17 15:57
Thank you so much, it works now! 🎉
Maybe adding a little disclaimer about not using `maven-gpg-plugin` prior to 1.6 could save precious time to the next person facing the same issue ;)

**Comment by IvanZosimov** [comment] 2023-11-20 08:10
@Lycoon, thanks for suggestion, I marked the issue with documentation label. As soon as we add additional information about this plugin to the action's documentation, I'll close this issue by myself.

**Comment by IvanZosimov** [comment] 2023-12-14 13:29
Hi, @Lycoon 👋 In [this PR](https://github.com/actions/setup-java/pull/570)  we added suggested changes to action's documentation. Thank you one more time 💌 !

I'm closing this issue now, If you have any additional questions feel free to reach out.

**Closed by IvanZosimov** 2023-12-14 13:29 UTC
Labels: documentation, external
