### ISSUE TITLE
Add support for JavaFX builds

### ISSUE THREAD

**Issue by airsquared** [actions/setup-java#18] opened 2019-08-27 01:48 UTC
Something like
```
- uses: actions/setup-java@v1
  with:
    java-version: '1.8'
    javafx: true
```

I believe Zulu just has `ca-fx` in the name of jdk versions with JavaFX.

**Comment by airsquared** [comment] 2019-08-29 03:40
I don't think there should a separate action for this, as it's just a regular JDK that also includes JavaFX. It also shouldn't be too complicated to add.

I think to add this feature, if the user wants the JavaFX version this line:
https://github.com/actions/setup-java/blob/91b87ac691493b05d11b6a73c292b0d5076d072e/src/installer.ts#L200 

would be changed to `let versions = ref.match(/ca-fx-jdk.*-/gi) || [];`.

**Comment by airsquared** [comment] 2019-08-31 03:02
@damccorm, @stephenmichaelf I created a PR: #19.

**Comment by giltene** [comment] 2019-09-27 03:12
Zulu Community has been making fx-bundled variants (...fx-jdkX.Y.Z... vs. ...jdkX.Y.Z...) available starting with 8 and 11 versions 8u202 and 11.0.3, and will continue to provide fx variants for all future updates of those LTS versions. So I can confirm that the parsing suggested in the referenced pull request will continue to work reliably.

**Comment by msgilligan** [comment] 2019-10-01 20:51
And, of course, you can now download JavaFX via maven/gradle since it has been decoupled from the JDK. That's how I've been happily doing it recently.

See:
* https://openjfx.io/openjfx-docs/#maven
* https://openjfx.io/openjfx-docs/#gradle

**Comment by giltene** [comment] 2019-10-01 22:44
The main driver for us building and providing FX-bundled versions of Zulu JDKs was driven making sure things work well in transitioning from Oracle JDK 8 to OpenJDK 8. Since Oracle JDK 8 had JavaFX bundled, none of the gradle/maven tooling stuff (as much as I personally use them. recommend them, and am happy/thankful for the community effort put into them) provides a "drop in", zero changes means for replacing the Oracle JDK. Bundling is there becuase many people's existing code and workflows assume FX-bundling.

Ironically, one of the most common drivers for people looking for a JavaFX-bundled JDK is *not* actual JavaFX application use, but "accidental"/unintentional use of some useful classes that happened to be part of JavaFX, but *not* part of the JDK, and were historically bundled in Oracle JDK 8. 

E.g. one of *the* most popular transitioning problem we've run into with plain OpenJDK 8 JDK is that is that OpenJDK 8 is "missing" [ javafx.util.Pair<K,V>](https://docs.oracle.com/javase/8/javafx/api/javafx/util/Pair.html). And yes, it's just a Pair class, and there are 342 other places you can get a good Pair class from. But *that* pair class was "part" of Oracle JDK 8, and it just worked there, and it is already in many people's code, so...

This then continues with OpenJDK 11, where people transitioning existing code from 8 to 11 run into these "missing" FX classes (on top of all their other post-Java-8 trasitioning pain). We've run into enough of that in the real world that we chose to regularly provide FX-bundled OpenJDK 11 with Zulu starting with 11.0.3.

**Comment by msgilligan** [comment] 2019-10-01 22:58
Thanks @giltene for the detailed explanation. Totally makes sense.

**Comment by giltene** [comment] 2019-11-03 04:56
I've created a separate pull request #27 that covers the requested feature but with a different syntax than the one proposed here: The change introduces a new java-package option that supports jre, jdk, and jdk+fx as accepted values (defaults to jdk and retains current behavior unless jre or jdk+fx is specified). I believe that this syntax (a single option to cover current and possible future package types) is preferable to having individual booleans per package type.

The action is available for testing as foo-actions/setup-java@master

**Comment by konradpabjan** [comment] 2019-11-22 20:20
Support for JavaFX has been added with #27 being merged in. Big thanks to @giltene ! 🎉

`README.md` has been updated to reflect the recent changes. As long as you're using `actions/setup-java@v1` then you should be able to use the most recent changes

**Closed by konradpabjan** 2019-11-22 20:20 UTC
