### ISSUE TITLE
README incorrectly states "cache-dependency-path" can be used

### ISSUE THREAD

**Issue by jmhodges** [actions/setup-java#571] opened 2023-12-19 11:40 UTC
**Description:**
The README's [Usage section](https://github.com/actions/setup-java/?tab=readme-ov-file#usage) says that the parameter `cache-dependency-path` can be used to set which pom files to cache from.

However, on a fresh repo with no prior GitHub Action runs adding that will cause GHA to emit a warning (not an error) saying that parameter doesn't exist:

```
Warning: Unexpected input(s) 'cache-dependency-path', valid inputs are ['java-version', 'java-version-file', 'distribution', 'java-package', 'architecture', 'jdkFile', 'check-latest', 'server-id', 'server-username', 'server-password', 'settings-path', 'overwrite-settings', 'gpg-private-key', 'gpg-passphrase', 'cache', 'job-status', 'token', 'mvn-toolchain-id', 'mvn-toolchain-vendor']
```

**Task version:**
I don't know what this is. This is with setup-java@v3. (Does that help?)

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  

```
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: |
          java/pom.xml
```

(with a pom at `./java/pom.xml` but this error happens before that's checked)

**Expected behavior:**
No warnings or errors and the caching should work as documented

**Actual behavior:**
It warns about the documented parameter not existing

**Comment by jmhodges** [comment] 2023-12-19 11:46
Ah, it seems that when you select the new Maven workflow via the GitHub website, the templated `.github/workflows/maven.yml` it creates uses `setup-java@v3`, not `setup-java@v4` which seems to be the latest?

**Comment by IvanZosimov** [comment] 2023-12-19 13:52
Hi, @jmhodges 👋 You're right, the cause of the issue is in the version of the action. Seems like the starter workflow doesn't reflect the recent changes in the major version of the action yet. Will work on that, thank you!

I'm closing this issue, if you have any additional questions, feel free to reach out.

**Closed by IvanZosimov** 2023-12-19 13:52 UTC
Labels: bug, needs triage
