### ISSUE TITLE
Add Support For GraalVM

### ISSUE THREAD

**Issue by acrastt** [actions/setup-java#465] opened 2023-03-13 21:52 UTC
**Description:**
This is a greate plugin after all, but there is one feature I would want to see:
I have been using GraalVM for a long time now. When I am trying to set up a Java environment with your plugin, it turns out there is no support for GraalVM Community/Enterprise Edition(CE or EE). I would love to see this plugin to add support for GraalVM and/or other famous vendors/distributions like SapMachine.
Here is the link for GraalVM: https://www.graalvm.org/

**Comment by IvanZosimov** [comment] 2023-03-14 08:47
Hello, @acrastt 👋 Thank you for the feature request! Unfortunately, your request is a duplicate of https://github.com/actions/setup-java/issues/195, you can check the current status there. I'm going to close this feature request as a duplicate right now, if you have any questions feel free to ask us.

**Closed by IvanZosimov** 2023-03-14 08:47 UTC
Labels: duplicate, feature request
