### ISSUE TITLE
Setup Java is resulting in Certificate Error since today

### ISSUE THREAD

**Issue by malluri-nlg** [actions/setup-java#472] opened 2023-03-24 21:00 UTC
Since today i get the error certificate has expired when running the setup-java action in my github project. It runs on Linux Runner.

I have changed nothing in the setup for a longer time and it did not have any problems until this afternoon. I was running the step with  version 11 

![image](https://user-images.githubusercontent.com/107141375/227640026-2013d8f1-817b-4bbe-a785-104b81eeab76.png)

**Comment by tarun-neem** [comment] 2023-03-24 21:11
I'm having the same issue

**Comment by bentonjimmy** [comment] 2023-03-24 21:12
Seems to be working again.

**Comment by quieterkali** [comment] 2023-03-24 21:14
Same issue

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/13971376/227642918-1b60d19e-75ea-4154-947a-9ccb5126837c.png">

**Comment by IvanZosimov** [comment] 2023-03-27 12:52
Hi, all 👋  ! Thanks for the issue we will investigate it and get back to you with updates!

**Comment by IvanZosimov** [comment] 2023-03-28 10:48
Hi, all 👋 As the problem is solved, I'm going to close this issue. Thanks for the fast reaction! ❤️

**Closed by IvanZosimov** 2023-03-28 10:48 UTC
Labels: bug
