### ISSUE TITLE
Allow choosing maven version

### ISSUE THREAD

**Issue by aochagavia** [actions/setup-java#316] opened 2022-04-07 15:00 UTC
**Description:**
I would like to be able to choose the maven version (instead of only the JDK).

**Justification:**
When using the latest maven version (3.8.5), `mvn package` hits a compiler bug in my project. My current workaround is to use a docker image (`maven:3.8.5-openjdk-11`) instead of `setup-java`, which is a pity because using docker directly loses the automatic caching.

**Are you willing to submit a PR?**
Sure! Just help me get started and I'll do the rest

**Comment by dmitry-shibanov** [comment] 2022-04-08 14:08
Hello @aochagavia. Thank you for your report. I'm going to close the issue as duplicate of https://github.com/actions/setup-java/issues/40 for more information please refer to the thread of the initial issue.

**Closed by dmitry-shibanov** 2022-04-08 14:08 UTC
Labels: feature request
