### ISSUE TITLE
JDK support distribution JBR (jetbrains runtime version)

### ISSUE THREAD

**Issue by Leslie-DD** [actions/setup-java#585] opened 2024-01-11 12:39 UTC
Some libraries like [jewel](https://github.com/JetBrains/jewel) require the JetBrains Runtime to work correctly, but setup-java not supported yet.
Will you support JBR, and When?

**Comment by aparnajyothi-y** [comment] 2024-01-16 06:57
Hello @Leslie-DD
Thank you for reporting this issue, We will investigate it and come back to you as soon as we have some information.

**Comment by Goooler** [comment] 2024-03-23 06:41
Duplicate of #399.

**Closed** 2024-12-12 22:21 UTC
Labels: feature request
